import type { CopyKey } from "@/lib/copy";

const translations: Partial<Record<CopyKey, string>> = {
    "seo.site.name": "Videospiel-Marketing | Marketing für Indie-Spiele",
    "seo.site.description":
      "TrapPlan hilft Game-Studios, Wishlists und Sales mit performanceorientiertem Marketing zu steigern.",
    "seo.about.title": "Über uns | TrapPlan Game-Marketing-Agentur",
    "seo.about.desc":
      "TrapPlan hilft Game-Studios, Wishlists und Sales mit performanceorientierten Marketing-Systemen zu steigern.",
    "seo.blog.title": "Gaming-Marketing-Blog | Trends & Tipps",
    "seo.blog.desc":
      "Bleib auf dem Laufenden mit Trends im Gaming-Marketing. TrapPlans Blog deckt Tipps, Case Studies und Strategien ab, damit Brands im Games-Markt erfolgreich sind.",
    "seo.our_cases.title": "Unsere Cases | Game-Marketing-Ergebnisse & Case Studies",
    "seo.our_cases.desc": "Ausgewählte Ergebnisse und Case Studies von TrapPlan.",
    "seo.no_wishlists.title": "Keine Wishlists auf Steam | Store-Page-Conversion verbessern",
    "seo.no_wishlists.desc":
      "Was tun, wenn deine Steam-Seite Traffic bekommt, aber die Wishlists nicht wachsen.",
    "seo.reddit_launch_support.title":
      "Reddit Launch Support: Organischer Steam-Traffic ohne Backlash",
    "seo.reddit_launch_support.desc":
      "Eine organische Reddit-Kampagne mit 15 Posts, um Steam-Wishlists zu steigern, ohne den üblichen Marketing-Backlash auszulösen.",
    "seo.pr_starter_pack.title": "PR Starter Pack: Die Coverage, die dein Game verdient",
    "seo.pr_starter_pack.desc":
      "PR-Outreach für Indie-Games: lesbares Press Release, gezielte Pitches, Follow-ups und eine klare Kontaktliste. Für Credibility und Steam-Wishlists.",
    "seo.tiktok_20.title": "TikTok Paket: 20 Videos für Game-Marketing-Kampagnen",
    "seo.tiktok_20.desc":
      "20 TikTok-Videos für dein Game: Hooks, Skripte, Editing und ein klarer Content-Plan für Wishlists und Awareness.",
    "seo.influencer_micro.title":
      "Influencer Micro Campaign: Kosteneffiziente Reichweite, die konvertiert",
    "seo.influencer_micro.desc":
      "Ein Micro-Influencer-Aktivierungs-Sprint für Games: Nischen-Creator-Selection, Outreach, Koordination, Tracking und ein klarer Report. Für sinnvolle Reichweite und Steam-Wishlists.",
    "seo.influencer_activation.title":
      "Influencer Activation für Games: Coverage, die konvertiert",
    "seo.influencer_activation.desc":
      "Strukturierte Influencer-Kampagnen: Sourcing, Outreach, Koordination, Tracking und Post-Campaign-Learnings. Wiederholbar, messbar und für Games gebaut.",
    "seo.paid_ads_setup.title":
      "Paid Ads Setup: Kampagnen richtig aufsetzen",
    "seo.paid_ads_setup.desc":
      "Wir setzen deine Paid-Ad-Kampagnen von A bis Z auf: Kanalwahl, Budget-Setup, Targeting und Creative-Placement. Danach übergeben wir das Konto. Monitoring/Optimierung sind nicht enthalten.",
    "seo.gameplay_trailer.title": "Gameplay Trailer: Ein Trailer, der konvertiert",
    "seo.gameplay_trailer.desc":
      "Ein kompletter Gameplay-Trailer für dein Game: klares Storytelling, saubere Captures, Pace, Editing und Lieferung bereit für Steam, YouTube und Medien.",
    "seo.steam_wishlist_calculator.title": "Steam-Wishlist-Rechner | Sales & Traffic-Ziele schätzen",
    "seo.steam_wishlist_calculator.desc":
      "Schätze erforderliche Wishlists, Traffic und Budget, um dein Steam-Sales-Ziel in Woche 1 zu erreichen.",
    "seo.steam_pricing_planner.title": "Steam-Preisplaner & Rechner | Regionales Preis-Tool",
    "seo.steam_pricing_planner.desc":
      "Berechne empfohlene Steam-Regionalpreise mit Kaufkraftparität (PPP) und Live-FX-Kursen.",
    "seo.steam_influencers_planner.title": "Steam-Influencer-Planer | Gaming-Creator nach Genre finden",
    "seo.steam_influencers_planner.desc":
      "Profi-Tool, um YouTube- und Twitch-Gaming-Influencer nach Genre und ähnlichen Games zu finden.",
    "seo.steam_festival_planner.title": "Steam-Festival-Planer | Events für dein Game finden",
    "seo.steam_festival_planner.desc":
      "Durchsuche Steam-Festivals und Sales, filtere nach Typ und Genre und match Events mit deinem Game via AppID-Analyse.",
    "seo.creative_content_pipeline.title":
      "Creative Content Pipeline für Steam- und Console-Games",
    "seo.creative_content_pipeline.desc":
      "Eine kontinuierliche Content-Pipeline für Steam- und Console-Games: Trailer, Shorts, Store-Assets und iterative Produktion mit Fokus auf Wishlist-Wachstum und Conversion.",
    "seo.paid_growth.title": "Paid Growth für Steam- und Console-Games",
    "seo.paid_growth.desc":
      "High-Ticket Paid Growth für Steam- und Console-Games: Channel-Strategie, sauberes Tracking, Attribution und strukturierter Handover.",
    "seo.game_launch_blueprint.title":
      "Game Launch Blueprint: Deine Strategie, unsere Standards.",
    "seo.game_launch_blueprint.desc":
      "Hör auf zu raten. Wir liefern das exakte Marketing-Framework, das Publisher nutzen: standardisiert, battle-tested und bereit, gemeinsam umzusetzen.",
    "seo.games_co_publishing.title": "Games Co-Publishing: Marketing- & Distribution-Partner.",
    "seo.games_co_publishing.desc":
      "Eine marketinggetriebene Co-Publishing-Partnerschaft mit Fokus auf Sichtbarkeit, Marktvalidierung, Audience Growth und kommerzielle Performance.",
    "seo.blog.masterclass.title":
      "Steam Next Fest: die Masterclass in Discovery",
    "seo.blog.masterclass.desc":
      "Ein Deep Dive (2026) zu Steam Next Fest: was jetzt zählt, die ersten 48 Stunden, Conversion-Signale, Demo-Page-Strategie, Influencer-Timing und wie du Guidance in Execution verwandelst.",
    "legal.content_rules.meta_title": "Content-Regeln | TrapPlan Nutzungsrichtlinien",
    "legal.content_rules.meta_desc": "Grundregeln für die Nutzung von TrapPlan-Inhalten und Assets.",
    "legal.copyright.meta_title": "Copyright-Richtlinie | Geistiges Eigentum von TrapPlan",
    "legal.copyright.meta_desc": "Copyright-Richtlinie für Inhalte der TrapPlan-Website.",
    "form_page.title": "Bring dein Game-Marketing\nauf das nächste Level",
    "form_page.subtitle":
      "Wir helfen dir, Ziele zu klären, die passenden Promotion-Formate zu wählen und mit einem klaren Plan zurückzukommen — auch wenn du noch nicht weißt, wo du anfangen sollst.",
    "form_page.bullet.01": "Auf deine Ziele abgestimmt",
    "form_page.bullet.02": "Leistungsstarke Marketing-Formate entdecken",
    "form_page.bullet.03": "Einen klaren, umsetzbaren Vorschlag erhalten",
    "work_with_us_form.field_full_name": "Vollständiger Name*",
    "work_with_us_form.field_company": "Firmenname*",
    "work_with_us_form.field_email": "du@deinefirma.com*",
    "work_with_us_form.field_message": "Erzähl uns von deinem Spiel oder wobei du Hilfe brauchst...",
    "work_with_us_form.subscribe": "Ich möchte gelegentlich Marketing-Tipps erhalten",
    "work_with_us_form.submit_sending": "Wird gesendet...",
    "work_with_us_form.submit": "Lass uns reden",
    "work_with_us_form.privacy_note": "Wir geben deine Daten niemals weiter. Nur ein Experte wird sich bei dir melden.",
    "work_with_us_form.success": "Danke! Wir melden uns bald.",
    "work_with_us_form.error_generic": "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    "work_with_us_form.error_network": "Senden fehlgeschlagen. Bitte erneut versuchen.",
    "form.get_a_quote.title": "ANGEBOT ANFORDERN",
    "form.get_a_quote.subtitle":
      "Lass uns über deine Aufgabe sprechen — wir kommen mit einem finalen Angebot zurück.",
    "form.get_a_quote.message_whatsapp": "Nachricht auf WhatsApp",
    "form.get_a_quote.card_title": "Lass uns zusammenarbeiten",
    "form.get_a_quote.field_name": "Name*",
    "form.get_a_quote.field_company": "Firmenname*",
    "form.get_a_quote.field_email": "Geschäftliche E-Mail*",
    "form.get_a_quote.submit_sending": "Wird gesendet...",
    "form.get_a_quote.submit_send": "Senden",
    "form.get_a_quote.success": "Danke! Wir melden uns bald.",
    "form.get_a_quote.error_generic": "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    "form.get_a_quote.error_network": "Senden fehlgeschlagen. Bitte erneut versuchen.",
    "blog_quote_banner.banner.title": "Brauchst du Hilfe mit deinem Game-Marketing-Plan?",
    "blog_quote_banner.banner.subtitle": "Sende eine kurze Anfrage und wir antworten mit den nächsten Schritten",
    "blog_quote_banner.banner.cta": "Angebot anfordern",
    "blog_quote_banner.modal.title": "Lass uns zusammenarbeiten",
    "blog_quote_banner.modal.subtitle": "Teile deine Daten und wir melden uns",
    "blog_quote_banner.modal.close": "Schließen",
    "blog_quote_banner.success": "Danke! Wir melden uns bald.",
    "blog_quote_banner.error_generic": "Etwas ist schiefgelaufen. Bitte erneut versuchen.",
    "blog_quote_banner.error_network": "Senden fehlgeschlagen. Bitte erneut versuchen.",
    "no_wishlists.ui.title": "Keine Wishlists auf Steam",
    "no_wishlists.ui.subtitle": "Eine kurze, praktische Seite zum Teilen. Keine externen Embeds, kein CDN-Content.",
    "no_wishlists.ui.reasons.title": "Häufige Gründe",
    "no_wishlists.ui.reasons.body": "Geringes Wishlist-Wachstum ist meist ein Konversionsproblem, kein Traffic-Problem. Das Versprechen der Store-Seite ist unklar, die Capsule generiert keine Klicks, oder die Seite passt nicht zum Traffic, den du sendest.",
    "no_wishlists.ui.fix.title": "Was zuerst beheben",
    "no_wishlists.ui.fix.body": "Beginne mit Positionierung, Capsule- und Kurztrailer-Klarheit, dann verbessere den oberen Seitenbereich (erster Scroll) und validiere mit sauberem Tracking.",
    "no_wishlists.ui.tools.title": "Nützliche Tools",
    "no_wishlists.ui.tools.body": "Nutze unseren Rechner, um realistische Ziele zu setzen und deine aktuelle Geschwindigkeit zu prüfen.",
    "no_wishlists.ui.tools.cta": "Steam-Wishlist-Rechner",
    "our_cases.ui.title": "Unsere Cases",
    "our_cases.ui.subtitle": "Eine kuratierte Auswahl an Ergebnissen. Wir teilen, was öffentlich nützlich ist, und halten sensible Details privat.",
    "our_cases.ui.view_case_study": "Case Study ansehen",
    "our_cases.ui.next_step": "NÄCHSTER SCHRITT",
    "our_cases.ui.next_step_title": "Ein ähnliches Ergebnis gewünscht?",
    "our_cases.ui.next_step_body": "Teile deinen Zeitplan und deine Ziele. Wir schlagen einen wiederholbaren Plan vor und zeigen relevante Beispiele.",
    "our_cases.ui.contact_us": "Kontaktiere uns",
    "studios_cases.ui.back_to_cases": "← Zurück zu Cases",
    "studios_cases.ui.case_snapshot": "CASE-ÜBERBLICK",
    "studios_cases.ui.client": "Kunde",
    "studios_cases.ui.date": "Datum",
    "studios_cases.ui.note": "Hinweis",
    "studios_cases.ui.note_body": "Diese Seite ist im Repository gespeichert und lädt keine externen Inhalte.",
    "studios_cases.ui.work_with_us": "Mit uns arbeiten",
    "studios_cases.ui.next_step": "NÄCHSTER SCHRITT",
    "studios_cases.ui.next_step_title": "Ein ähnliches Ergebnis gewünscht?",
    "studios_cases.ui.next_step_body": "Teile deine aktuelle Phase und Einschränkungen. Wir schlagen einen wiederholbaren Plan vor.",
    "studios_cases.ui.contact_us": "Kontaktiere uns",
    "studios_cases.ui.summary": "Zusammenfassung",
    "studios_cases.ui.no_sections": "Dieser Case hat noch keine detaillierten Abschnitte.",
    "blog.ui.sidebar_title": "Trap Plan\nBlog",
    "blog.ui.sidebar_subtitle": "Notizen, Leitfäden und praktische Marketing-Systeme für Games.",
    "blog.ui.sidebar_latest": "Neueste",
    "blog.ui.sidebar_all": "Alle",
    "pr_starter_pack.ui.hero.body_connector_1": ". Ein guter Artikel wirkt wie ein",
    "pr_starter_pack.ui.hero.body_connector_2": "und bringt mehr Spieler dazu,",
    "blog.masterclass.s01.title": 'Steam Next Fest: Tausende Spiele werden konkurrieren, aber wie erzielst du Ergebnisse?',
    "blog.masterclass.s01.p01": 'Steam Next Fest ist kein Ort mehr, an dem es reicht, einfach aufzutauchen. Mit Tausenden von Demos, die gleichzeitig konkurrieren, wird die Plattform vorbereitete Projekte belohnen und diejenigen bestrafen, die das Festival als Ausgangspunkt behandeln. Dieser Leitfaden erklärt, was 2026 wirklich zählt, welche Signale Steam beachtet und wie du die Woche in messbaren Schwung verwandelst.',
    "blog.masterclass.s02.title": 'Das Februar-Fest steht vor der Tür und ich habe gerade meine Demo fertig. Soll ich jetzt einsteigen?',
    "blog.masterclass.s02.p01": 'Jordan warnt, dass Next Fest nicht mehr die „magische Kugel“ von 2023 ist, als weniger als 1.000 Spiele teilnahmen. Heute, mit über 3.000 regelmäßig konkurrierenden Spielen, ist die Umgebung weit weniger nachsichtig.',
    "blog.masterclass.s02.p02": 'Wenn du das Festival nutzt, um dein Marketing von Grund auf zu starten, machst du wahrscheinlich einen Fehler. Die ideale Strategie ist, deine Demo mindestens einige Monate vor dem Event zu veröffentlichen, um Bugs zu beheben und erste Traktion aufzubauen.',
    "blog.masterclass.s02.p03": 'Spiele, die mit einer substanziellen Wishlist-Basis zu Next Fest kommen, wirken als Multiplikator für bestehenden Schwung, während diejenigen, die kalt starten, oft vom Algorithmus begraben werden.',
    "blog.masterclass.s03.title": 'Man sagt, Livestreams funktionieren nicht mehr. Kann ich die Übertragung überspringen?',
    "blog.masterclass.s03.p01": 'Die Landschaft hat sich verändert: Steam hat Livestreams de-priorisiert und sie bieten nicht mehr den massiven Sichtbarkeitsschub von früher. Das ist jedoch kein Grund, sie komplett zu überspringen, da der dedizierte Bereich für aktive Übertragungen weiterhin existiert und eine Entdeckungsebene bietet.',
    "blog.masterclass.s03.p02": 'Anstatt dich mit 10-stündigen Live-Sessions auszubrennen, nutze Tools wie Robostreamer, um hochwertiges Gameplay-Material in Schleife abzuspielen oder, noch besser, einen bekannten Influencer, der dein Spiel spielt. So kannst du eine Präsenz in der Rotation aufrechterhalten, ohne Ressourcen zu verbrauchen, die besser für die Interaktion mit deiner Community auf Discord eingesetzt werden.',
    "blog.masterclass.s04.title": 'Der Steam-Algorithmus hat sich Ende 2024 geändert. Was muss ich über die ersten 48 Stunden wissen?',
    "blog.masterclass.s04.p01": 'Dies ist ein kritisches Zeitfenster: In den ersten zwei Tagen des Festivals erhalten alle Spiele ungefähr gleiche Sichtbarkeit, da die Listen zufällig sortiert werden.',
    "blog.masterclass.s04.p02": 'Nach diesen 48 Stunden wechselt Steam jedoch zu Machine-Learning-Modellen, die den Feed für jeden angemeldeten Nutzer basierend auf seinen spezifischen Interessen und dem, was seine Freunde spielen, personalisieren.',
    "blog.masterclass.s04.p03": 'Die Interaktionsdaten, die Steam während dieser ersten zwei Tage sammelt — Klicks, Downloads und Interaktionen — bilden die Grundlage dafür, wie der Algorithmus dein Spiel für den Rest der Woche kategorisiert und empfiehlt. Im Wesentlichen „trainieren“ die ersten 48 Stunden das System darüber, wer dein Publikum ist.',
    "blog.masterclass.s05.title": 'Verfolgt Steam tatsächlich, ob Leute meine Demo durchspielen?',
    "blog.masterclass.s05.p01": 'Überraschenderweise nein. In offiziellen Q&A-Sessions erklärte Valve, dass Demo-Abschlussraten und Gesamtspielzeit keine entscheidenden Signale für die Post-Fest-Sichtbarkeit sind. Sie glauben, es wäre unfair, eine 20-minütige narrative Erfahrung gegen ein Roguelike zu bewerten, das endlos spielbar ist.',
    "blog.masterclass.s05.p02": 'Stattdessen konzentriert sich Steam auf „Interaktionssignale“: Wie viele Personen deine Store-Seite besucht, die Demo heruntergeladen und vor allem wie viele dein Projekt auf die Wishlist gesetzt oder ihm gefolgt sind.',
    "blog.masterclass.s05.p03": 'Konzentriere dich auf Konversion — einen Klick in eine Wishlist verwandeln — anstatt zu versuchen, Spieler stundenlang in der Demo zu halten.',
    "blog.masterclass.s06.title": 'Warum eine separate Seite für die Demo verwenden, wenn ich einfach einen Button auf der Hauptseite hinzufügen kann?',
    "blog.masterclass.s06.p01": 'Eine separate Demo-Seite ist dein wichtigstes Werkzeug zum Aufbau von Social Proof. Sie ermöglicht es dir, spezifische Bewertungen für die Demo zu sammeln, was ein starkes Signal ist. Wenn du viele positive Bewertungen erhältst, kann dir das helfen, in den „Trending Free“-Charts zu landen und eine massive Welle neuen Traffics zu bringen.',
    "blog.masterclass.s06.p02": 'Umgekehrt, wenn die Demo negatives Feedback erhält, kannst du die separate Seite einfach entfernen, ohne den Ruf deiner Hauptstore-Seite zu beeinträchtigen.',
    "blog.masterclass.s06.p03": 'Es ist ein sicherer Weg, die Marktreife deines Produkts zu testen, und wenn du noch nervös bist, nutze zuerst die Steam Playtest-Tools, wo Feedback privat bleibt.',
    "blog.masterclass.s07.title": 'Ich habe am Tag vor dem Fest E-Mails an Influencer geschickt. Warum antwortet niemand?',
    "blog.masterclass.s07.p01": 'Du bist wahrscheinlich zu spät dran. Effektive PR-Arbeit mit Presse und Creatorn muss mindestens einen Monat im Voraus beginnen. Dein erster Kontakt sollte vier Wochen vor dem Start stattfinden, mit einem Key und einem klaren Embargo-Datum, damit Creator Zeit haben, ihren Content zu planen.',
    "blog.masterclass.s07.p02": 'Mache eine Woche vor dem Event ein Follow-up mit einer Erinnerung und einen letzten „Push“ am Eröffnungstag.',
    "blog.masterclass.s07.p03": 'Spamme nicht jeden an; erstelle eine kuratierte Liste von Nischen-Creatorn, die dein Genre wirklich mögen. Denke daran, dass mehr als drei E-Mails normalerweise die Grenze zur Belästigung überschreiten und deinen langfristigen Ruf schädigen können.',
    "blog.masterclass.s08.title": 'Wie bringe ich Spieler dazu, am zweiten oder dritten Tag des Festivals zurückzukommen?',
    "blog.masterclass.s08.p01": 'Nutze „Retention durch Engagement“-Taktiken, um deine Community aktiv zu halten. Tiny Glade hat das brillant gemacht, indem sie tägliche Bauthemen anboten, während Tears of Metal tägliche Gameplay-Modifikatoren einführte, um die Erfahrung frisch zu halten.',
    "blog.masterclass.s08.p02": 'Du kannst exklusive kosmetische Belohnungen für das vollständige Spiel freischalten, wenn Spieler die Demo in bestimmten Zeitfenstern abschließen, oder tägliche Devlogs mit Vorschauen auf kommende Features veranstalten.',
    "blog.masterclass.s08.p03": 'Einer der mächtigsten Züge ist die Nutzung von FOMO, indem du eine einzigartige Belohnung für das Spielen innerhalb der ersten 24 Stunden anbietest und so hohe Leistung während des kritischen 48-Stunden-Datenerfassungsfensters sicherstellst.',
    "blog.masterclass.s09.title": 'Mein Spiel hat Bugs, aber soll ich während des Fests weiter neue Features entwickeln?',
    "blog.masterclass.s09.p01": 'Vergiss neue Features während der Festivalwoche. Dein einziger Job jetzt ist „Feuerwehr spielen“. Sei 24/7 verfügbar, um kritische Bugs sofort zu beheben und auf Feedback zu reagieren.',
    "blog.masterclass.s09.p02": 'Eine schnelle Antwort eines Entwicklers ist der beste Weg, einen frustrierten Spieler in einen leidenschaftlichen Fan zu verwandeln. Wenn du Bug-Reports während Next Fest ignorierst, verlierst du Spieler-Goodwill, der mit keiner Menge an Werbung zurückgekauft werden kann.',
    "blog.masterclass.s09.p03": 'Richte automatisierte Bug-Reporting-Tools direkt in deinem Hauptmenü oder Pausenbildschirm ein, damit Spieler dich sofort erreichen können, anstatt eine negative Bewertung zu hinterlassen.',
    "blog.masterclass.s10.title": 'Ich habe von „Achievements“ in Demos gehört. Ist das wirklich eine gute Idee?',
    "blog.masterclass.s10.p01": 'Es ist nicht nur eine gute Idee; es ist eine Notwendigkeit für Engagement. Steam Achievements zu deiner Demo hinzuzufügen ist ein bewährter Weg, Spieler zu motivieren.',
    "blog.masterclass.s10.p02": 'Füge ein einfaches Achievement in den ersten 15 Minuten ein, um den Spieler zu „haken“ und ihm zu zeigen, dass Belohnungen erreichbar sind. Füge ein weiteres für das Abschließen der Demo als letzten Anreiz hinzu, die Erfahrung zu beenden.',
    "blog.masterclass.s10.p03": 'Eine Mischung aus lustigen und schwierigen Achievements verwandelt eine einfache Demo in eine lohnende Herausforderung, die direkt mit dem Wunsch des Spielers korreliert, diesen Fortschritt in das vollständige Spiel zu übertragen, indem er es auf die Wishlist setzt.',
    "blog.masterclass.s11.title": 'Warum sollte ich mein Spiel nicht sofort nach dem Festival veröffentlichen?',
    "blog.masterclass.s11.p01": 'Es ist eine häufige Falle: Der Wunsch, „das Eisen zu schmieden, solange es heiß ist“, führt viele Entwickler dazu, genau zur gleichen Zeit wie Hunderte anderer Next-Fest-Teilnehmer zu launchen.',
    "blog.masterclass.s11.p02": 'Während dieses Zeitfensters ist der Wettbewerb um einen Platz in „Neu und im Trend“ ungewöhnlich hoch, und du riskierst, von größeren Studios mit größeren Budgets verdrängt zu werden.',
    "blog.masterclass.s11.p03": 'Sofern du nicht mindestens 20.000 Wishlists hast und sicher bist, einer der absoluten Top-Performer des Fests gewesen zu sein, ist es oft besser zu warten. Lass den Markt abkühlen, aktualisiere weiter deine Demo und halte die Verbindung zu deinem neuen Publikum für ein stabileres Launch-Fenster aufrecht.',
    "ui.pagination.previous": "Zurück",
    "ui.pagination.next": "Weiter",
    "ui.pagination.page_aria": "Zur Seite {n}",
    "ui.mobile_cta.label": "Angebot anfordern",
    "ui.cookie.title": "Wir verwenden Cookies.",
    "ui.cookie.body": "Ein minimales Set an Cookies hält die Seite am Laufen. Mit deiner Zustimmung helfen anonyme Analysen uns zu sehen, welche Guides Studios wirklich helfen. Keine Drittanbieter-Tracker werden aktiviert, bis du zustimmst.",
    "ui.cookie.accept": "Alle akzeptieren",
    "ui.cookie.reject": "Nicht erforderliche ablehnen",
    "ui.cookie.learn_more": "Mehr erfahren",
    "ui.breadcrumb.home": "Startseite",
    "ui.breadcrumb.blog": "Blog",
    "ui.breadcrumb.our_cases": "Fallstudien",
    "ui.breadcrumb.about": "Über uns",
    "services_hub.title": "Alles, was wir für Spielestudios tun.",
    "services_hub.subtitle": "Wähle den Service, den du heute brauchst, oder kombiniere mehrere zu einem vollständigen Projekt. Alles vom gleichen Senior-Team geführt, das Spiele aus Erfahrung kennt.",
    "services_hub.cta_learn_more": "Mehr erfahren →",
    "services_hub.packages_title": "Pakete mit festem Umfang",
    "services_hub.packages_subtitle": "Kleinere Engagements mit klarem Preis, klarem Umfang und klarem Ergebnis.",
};

export default translations;
