import type { CopyKey } from "@/lib/copy";

const translations: Partial<Record<CopyKey, string>> = {
    "nav.about_us": "Sobre nosotros",
    "nav.services": "Servicios",
    "nav.our_cases": "Casos",
    "nav.blog": "Blog",
    "cta.work_with_us": "Trabaja con nosotros",
    "cta.read_the_blog": "Leer el blog",
    "cta.lets_talk": "Hablemos",
    "hero.badge.01": "Marketing de rendimiento",
    "hero.badge.02": "Redes sociales",
    "hero.badge.03": "Estrategia go-to-market",
    "hero.kicker": "Marketing para videojuegos",
    "hero.subhead":
      "Ayudamos a estudios, publishers y equipos indie a lanzar, crecer y escalar juegos con marketing pulido y orientado a resultados.",
    "hero.body":
      "Estrategia primero, ejecución después — pensado para Steam y para las limitaciones reales de producción.",
    "hero.cta_contact": "Contáctanos",
    "cases.title": "Casos de éxito",
    "cases.subtitle": "Campañas reales para juegos reales.",
    "cases.cta_view_case": "Ver caso",
    "cases.cta_view_all": "Ver todos los casos",
    "cases.fallback_metric": "Caso",
    "cases.metric.war_thunder_youtube_europe": "Más de 1M de vistas al mes",
    "cases.metric.enlisted_twitch_ads": "Más de 1.500 nuevos jugadores",
    "cases.metric.crossout_new_players": "Más alcance en Europa y EE. UU.",
    "cases.metric.war_thunder_performance_based": "Activaciones mensuales con KPIs claros",
    "cases.metric.world_of_tanks_usa": "Campañas en EE. UU. con entrega estructurada",
    "cases.metric.brief_for_youtube_twitch": "Briefs y ejecución con dirección clara",
    "cases.result.enlisted_twitch_ads": "Más de 1.500 nuevos jugadores",
    "cases.result.crossout_new_players": "Más alcance en Europa y EE. UU.",
    "cases.result.war_thunder_performance_based": "Activaciones mensuales con KPIs claros",
    "cases.result.world_of_tanks_usa": "Campañas en EE. UU. con entrega estructurada",
    "cases.result.brief_for_youtube_twitch": "Briefs y ejecución con dirección clara",
    "cases.result.war_thunder_youtube_europe": "Más de 1M de vistas al mes",
    "cases.desc_override.war_thunder_youtube_europe":
      "Campañas de YouTube Ads para War Thunder que superan 1.000.000 de vistas al mes en regiones clave de Europa.",
    "services.title": "Servicios globales",
    "services.subtitle":
      "Sistemas completos, de principio a fin, para estudios que quieren resultados predecibles — no tareas sueltas.",
    "services.panel.blueprint.title": "Plan de lanzamiento",
    "services.panel.blueprint.desc":
      "Posicionamiento, mensajes, calendario y mix de canales. Un plan claro que reduce el caos, alinea al equipo y hace la ejecución predecible.",
    "services.panel.blueprint.ghost": "ESTRATEGIA / MENSAJE / EJECUCIÓN",
    "services.panel.paid_growth.title": "Crecimiento de pago",
    "services.panel.paid_growth.desc":
      "Configuramos campañas pagadas como debe ser: canales, tracking, segmentación y estructura. Control, medición y entrega limpia.",
    "services.panel.paid_growth.ghost": "ADQUISICIÓN / ANALÍTICA / ESCALA",
    "services.panel.creative.title": "Pipeline creativo",
    "services.panel.creative.desc":
      "Un pipeline constante para trailers, shortform y assets de tienda. Diseñado para velocidad, iteración y distribución nativa por plataforma.",
    "services.panel.creative.ghost": "PRODUCCIÓN | ADAPTACIÓN | PERFORMANCE",
    "services.mobile_hint": "Toca para explorar",
    "packages.title": "Paquetes listos para usar",
    "packages.price_label": "Precio:",
    "packages.cta_learn_more": "Saber más",
    "packages.media_video_label": "Vídeo",
    "packages.card.reddit.title": "Soporte de lanzamiento\nen Reddit",
    "packages.card.reddit.desc":
      "Gestionamos la presencia de tu estudio en Reddit desde su cuenta oficial. 15 publicaciones en los subreddits adecuados, escritas para encajar en cada comunidad y generar wishlists.",
    "packages.card.pr_starter.title": "Pack inicial de PR",
    "packages.card.pr_starter.desc":
      "PR para conseguir cobertura: nota de prensa clara, pitches segmentados, follow-ups y lista completa de contactos. Diseñado para credibilidad y wishlists en Steam.",
    "packages.card.influencer_micro.title": "Microcampaña\ncon influencers",
    "packages.card.influencer_micro.desc":
      "Identificamos creadores de nicho, coordinamos activaciones de contenido y medimos rendimiento. Eficiente en coste, escalable y enfocada en alcance de calidad.",
    "packages.card.tiktok_20.title": "Paquete TikTok:\n20 vídeos",
    "packages.card.tiktok_20.desc":
      "20 vídeos de TikTok a medida para tu juego. Nos encargamos del concepto, producción y formato, alineados con tendencias de plataforma y comportamiento de la audiencia.",
    "packages.card.paid_ads_setup.title": "Configuración de anuncios de pago",
    "packages.card.paid_ads_setup.desc":
      "Configuramos tus campañas de pago de principio a fin: selección de canales, presupuesto, segmentación y placements creativos. Tras el lanzamiento, entregamos la cuenta. No incluye monitorización u optimización continua.",
    "packages.card.gameplay_trailer.title": "Tráiler de gameplay",
    "packages.card.gameplay_trailer.desc":
      "Un tráiler completo y de alta calidad hecho para tu juego. Storytelling claro, captura pulida, ritmo, edición y entrega lista para Steam, YouTube y distribución a medios.",
    "paid_ads_setup.ui.hero.title_line_1": "Anuncios de pago.",
    "paid_ads_setup.ui.hero.title_line_2": "Configura una vez. Lanza limpio.",
    "paid_ads_setup.ui.hero.body":
      "Configuramos tus campañas paid de principio a fin: selección de canales, configuración de presupuesto, segmentación y placements creativos. Tras el lanzamiento, te entregamos la cuenta. No incluye monitorización u optimización continua.",
    "paid_ads_setup.ui.hero.cta": "Empecemos",
    "paid_ads_setup.ui.hero.price": "Precio: €2 000",
    "paid_ads_setup.ui.hero.image_alt": "Vista previa de la configuración de anuncios",
    "paid_ads_setup.ui.section2.title_line_1": "Deja de quemar presupuesto.",
    "paid_ads_setup.ui.section2.title_line_2": "Arregla la base.",
    "paid_ads_setup.ui.section2.p1":
      "La mayoría de campañas paid fallan porque la configuración está mal: tracking incorrecto, estructura equivocada, targeting poco claro y creatividades que no encajan.",
    "paid_ads_setup.ui.section2.p2":
      "Dejamos la cuenta configurada como debe ser para que lances con confianza y mantengas el control después del handoff.",
    "paid_ads_setup.ui.section2.image_alt": "Vista general de la configuración de campaña",
    "paid_ads_setup.ui.section3.image_alt": "Mockup de configuración de anuncios",
    "paid_ads_setup.ui.section3.title": "La configuración de anuncios de pago",
    "paid_ads_setup.ui.section3.bullet.channel_title": "Selección de canales:",
    "paid_ads_setup.ui.section3.bullet.channel_text":
      "elegimos las plataformas que encajan con tu audiencia y tu funnel.",
    "paid_ads_setup.ui.section3.bullet.budget_title": "Configuración de presupuesto:",
    "paid_ads_setup.ui.section3.bullet.budget_text":
      "estructuramos el gasto para que sea controlable y medible.",
    "paid_ads_setup.ui.section3.bullet.targeting_title": "Configuración de targeting:",
    "paid_ads_setup.ui.section3.bullet.targeting_text":
      "audiencias, exclusiones e higiene de cuenta.",
    "paid_ads_setup.ui.section3.bullet.creative_title": "Placement creativo:",
    "paid_ads_setup.ui.section3.bullet.creative_text":
      "formatos y ubicaciones correctas por canal.",
    "paid_ads_setup.ui.section3.bullet.handoff_title": "Handoff:",
    "paid_ads_setup.ui.section3.bullet.handoff_text":
      "te entregamos una cuenta limpia lista para operar.",
    "paid_ads_setup.ui.section3.cta": "Empecemos",
    "paid_ads_setup.ui.section4.title": "Cómo funciona",
    "paid_ads_setup.ui.section4.step1.title": "Alcance",
    "paid_ads_setup.ui.section4.step1.text":
      "Alineamos objetivos, funnel, presupuesto y limitaciones.",
    "paid_ads_setup.ui.section4.step2.title": "Configurar",
    "paid_ads_setup.ui.section4.step2.text":
      "Configuramos estructura, segmentación, placements y tracking.",
    "paid_ads_setup.ui.section4.step3.title": "Lanzar",
    "paid_ads_setup.ui.section4.step3.text":
      "Te ayudamos a lanzar con los ajustes correctos en su sitio.",
    "paid_ads_setup.ui.section4.step4.title": "Entrega",
    "paid_ads_setup.ui.section4.step4.text":
      "Tienes acceso completo y una configuración clara que puedes gestionar.",
    "paid_ads_setup.ui.section4.cta": "Empecemos",
    "seo.site.name": "Marketing de videojuegos | Marketing para juegos indie",
    "seo.site.description": "TrapPlan ayuda a estudios de juegos a aumentar wishlists y ventas con marketing basado en rendimiento.",
    "seo.about.title": "Sobre nosotros | TrapPlan Agencia de Marketing de Videojuegos",
    "seo.about.desc": "TrapPlan ayuda a estudios de juegos a aumentar wishlists y ventas con sistemas de marketing basados en rendimiento.",
    "seo.blog.title": "Blog de marketing para videojuegos | Tendencias y consejos",
    "seo.blog.desc":
      "Mantente al día con las últimas tendencias de marketing de influencers en videojuegos. El blog de TrapPlan comparte tips, casos y estrategias para crecer.",
    "seo.our_cases.title": "Nuestros casos | Resultados y casos de estudio de marketing gaming",
    "seo.our_cases.desc": "Resultados seleccionados y casos de estudio de TrapPlan.",
    "seo.no_wishlists.title": "Sin wishlists en Steam | Mejora la conversión de tu página",
    "seo.no_wishlists.desc": "Qué hacer cuando tu página de Steam recibe tráfico pero las wishlists no crecen.",
    "seo.reddit_launch_support.title": "Soporte de lanzamiento en Reddit: tráfico orgánico sin backlash",
    "seo.reddit_launch_support.desc":
      "Campaña orgánica de 15 posts en Reddit diseñada para impulsar wishlists en Steam sin provocar el típico rechazo al marketing.",
    "seo.pr_starter_pack.title": "Pack inicial de PR: consigue la cobertura que tu juego merece",
    "seo.pr_starter_pack.desc":
      "PR para indies: nota de prensa clara, pitches segmentados, follow-ups y una lista de contactos. Para credibilidad y wishlists en Steam.",
    "seo.tiktok_20.title": "Paquete TikTok: 20 vídeos para campañas de marketing gaming",
    "seo.tiktok_20.desc":
      "20 vídeos de TikTok para tu juego: hooks, guiones, edición y un plan de contenido pensado para awareness y wishlists.",
    "seo.influencer_micro.title": "Microcampaña con influencers: alcance eficiente que convierte",
    "seo.influencer_micro.desc":
      "Sprint de microinfluencers para juegos: selección de nicho, outreach, coordinación, tracking y reporte. Enfocado en alcance de calidad y wishlists.",
    "seo.influencer_activation.title": "Activación con influencers para juegos: cobertura que convierte",
    "seo.influencer_activation.desc":
      "Campañas de influencers estructuradas: sourcing, outreach, coordinación, tracking y aprendizajes post-campaña. Repetible, medible y diseñado para juegos.",
    "seo.paid_ads_setup.title": "Configuración de anuncios de pago: lanza bien tus campañas",
    "seo.paid_ads_setup.desc":
      "Configuramos tus campañas paid de principio a fin: canales, presupuesto, segmentación y placements. Tras el lanzamiento, entregamos la cuenta.",
    "seo.gameplay_trailer.title": "Tráiler de gameplay: un tráiler para convertir",
    "seo.gameplay_trailer.desc":
      "Tráiler gameplay completo: storytelling, captura pulida, ritmo y edición. Listo para Steam, YouTube y distribución a medios.",
    "seo.steam_wishlist_calculator.title": "Calculadora de wishlists de Steam | Estima ventas y tráfico",
    "seo.steam_wishlist_calculator.desc": "Estima wishlists, tráfico y presupuesto necesarios para alcanzar tu objetivo de ventas en la primera semana.",
    "seo.steam_pricing_planner.title": "Planificador y calculadora de precios en Steam | Herramienta regional",
    "seo.steam_pricing_planner.desc":
      "Calcula precios regionales recomendados en Steam usando PPP (paridad de poder adquisitivo) y tipos de cambio.",
    "seo.steam_influencers_planner.title": "Planificador de influencers para Steam | Encuentra creadores gaming",
    "seo.steam_influencers_planner.desc":
      "Herramienta profesional para descubrir influencers gaming en YouTube y Twitch según género y juegos similares.",
    "seo.steam_festival_planner.title": "Planificador de festivales de Steam | Eventos para tu juego",
    "seo.steam_festival_planner.desc":
      "Explora festivales y rebajas de Steam, filtra por tipo y género y encuentra eventos adecuados usando análisis de AppID.",
    "seo.creative_content_pipeline.title": "Pipeline creativo de contenido para Steam y consolas",
    "seo.creative_content_pipeline.desc":
      "Pipeline continuo de trailers, shorts y assets de tienda con producción iterativa enfocada en crecimiento y conversión de wishlists.",
    "seo.paid_growth.title": "Crecimiento de pago para Steam y consolas",
    "seo.paid_growth.desc":
      "Paid growth premium: estrategia de canales, tracking limpio, atribución y handoff estructurado.",
    "seo.game_launch_blueprint.title": "Blueprint de lanzamiento: tu estrategia, nuestros estándares",
    "seo.game_launch_blueprint.desc":
      "Deja de adivinar. Te damos el framework de marketing que usan publishers: estandarizado, probado y listo para ejecutar.",
    "seo.games_co_publishing.title": "Co-publishing: socio de marketing y distribución",
    "seo.games_co_publishing.desc":
      "Alianza de co-publicación impulsada por marketing: visibilidad, validación de mercado, crecimiento de audiencia y rendimiento comercial.",
    "seo.blog.masterclass.title": "Steam Next Fest: masterclass de descubrimiento",
    "seo.blog.masterclass.desc":
      "Análisis 2026 de Steam Next Fest: qué importa, primeras 48h, señales de conversión, estrategia de demo page, timing con influencers y ejecución.",
    "legal.content_rules.meta_title": "Reglas de contenido | Directrices de uso de TrapPlan",
    "legal.content_rules.meta_desc": "Reglas básicas para usar el contenido y los recursos de TrapPlan.",
    "legal.content_rules.title": "Reglas de contenido",
    "legal.content_rules.lede": "Esta página define cómo se pueden usar los materiales de TrapPlan.",
    "legal.content_rules.section1.title": "1. Propiedad",
    "legal.content_rules.section1.body":
      "Salvo indicación expresa, todo el contenido de este sitio web pertenece a TrapPlan.",
    "legal.content_rules.section2.title": "2. Uso permitido",
    "legal.content_rules.section2.body":
      "Puedes compartir enlaces a nuestras páginas y citar extractos breves con la atribución adecuada.",
    "legal.content_rules.section3.title": "3. Uso prohibido",
    "legal.content_rules.section3.body":
      "No puedes copiar, republicar ni vender nuestros materiales como si fueran tuyos. Tampoco puedes usar nuestros recursos de marca de forma que implique una asociación sin permiso escrito.",
    "legal.content_rules.section4.title": "4. Solicitudes",
    "legal.content_rules.section4.body":
      "Si quieres reutilizar materiales más allá de lo descrito arriba, contáctanos mediante el formulario del sitio.",
    "legal.copyright.meta_title": "Política de copyright | Propiedad intelectual de TrapPlan",
    "legal.copyright.meta_desc": "Política de copyright del contenido del sitio de TrapPlan.",
    "legal.copyright.title": "Política de copyright",
    "legal.copyright.lede":
      "Aquí explicamos cómo se protege el contenido de TrapPlan y cómo puedes utilizarlo.",
    "legal.copyright.section1.title": "Aviso de copyright",
    "legal.copyright.section1.body":
      "Todos los textos, diseños y materiales de este sitio están protegidos por copyright y otras leyes de propiedad intelectual aplicables.",
    "legal.copyright.section2.title": "Permiso",
    "legal.copyright.section2.body":
      "Puedes referenciar y enlazar nuestras páginas. Si deseas republicar o reproducir una parte sustancial del contenido, solicita permiso.",
    "legal.copyright.section3.title": "Reportes",
    "legal.copyright.section3.body":
      "Si crees que tu obra con copyright se usa en este sitio de forma que constituya infracción, contáctanos e incluye los detalles relevantes.",
    "footer.tagline":
      "Desde el primer anuncio hasta el lanzamiento global. Flujos de trabajo de marketing de nivel profesional, diseñados específicamente para estudios de videojuegos que quieren mejores resultados y cero caos.",
    "footer.all_rights_reserved": "Todos los derechos reservados.",
    "footer.notice_at_collection": "Aviso en la recopilación",
    "footer.privacy_choices": "Tus opciones de privacidad",
    "about.hero.title": "Sobre TrapPlan",
    "about.hero.subtitle":
      "Ayudamos a estudios de videojuegos a crecer de forma predecible en wishlists y ventas combinando estrategia, mensajes claros y ejecución orientada al rendimiento.",
    "about.hero.cta_primary": "Trabaja con nosotros",
    "about.hero.cta_secondary": "Leer el blog",
    "about.how_we_think.title": "Cómo pensamos",
    "about.how_we_think.body":
      "Creamos sistemas que hacen el marketing repetible. No es “más actividad”: es una cadena clara desde el posicionamiento hasta los assets, la distribución y la medición.",
    "about.principle.01.title": "Estrategia según tu etapa",
    "about.principle.01.body":
      "Nada de consejos genéricos. Convertimos tu realidad (equipo, plazos, audiencia y assets de la store) en un plan de lanzamiento y crecimiento ejecutable.",
    "about.principle.02.title": "Mensajes que convierten",
    "about.principle.02.body":
      "Te ayudamos a comunicar la promesa central de tu juego en Steam, creatividades y campañas, para que el jugador correcto lo entienda rápido.",
    "about.principle.03.title": "Ejecución con medición",
    "about.principle.03.body":
      "Trabajamos con ciclos estructurados, tracking limpio, responsables claros y post-mortems para que cada iteración mejore el resultado.",
    "about.what_you_get.title": "Qué obtienes",
    "about.what_you_get.body": "Una colaboración estructurada que reduce el caos y hace medibles las decisiones.",
    "about.outcome.label": "RESULTADO",
    "about.outcome.01.title": "Prioridades claras",
    "about.outcome.01.body": "Un plan que conecta hitos con acciones de marketing, con responsables y fechas límite.",
    "about.outcome.02.title": "Mejor conversión",
    "about.outcome.02.body": "Mensajes y assets optimizados para reducir dudas y aumentar la intención.",
    "about.outcome.03.title": "Tracking limpio",
    "about.outcome.03.body": "Una capa de medición para ver qué canales y creatividades funcionan.",
    "about.outcome.04.title": "Aprendizajes repetibles",
    "about.outcome.04.body": "Post-mortems e iteraciones que acumulan aprendizaje en lugar de reiniciar.",
    "about.principles.title": "Principios",
    "about.principles.body": "Cómo colaboramos con estudios: lo no negociable.",
    "about.value.04.title": "Proceso transparente y predecible",
    "about.value.04.body":
      "Siempre sabes qué hacemos, por qué y cómo se ve el éxito. Entregables claros, cadencia y registro de decisiones.",
    "about.value.05.title": "Mentalidad de performance",
    "about.value.05.body": "Nos enfocamos en lo que mueve la aguja: conversión, velocidad de wishlists y canales de adquisición repetibles.",
    "about.value.06.title": "Hecho para estudios",
    "about.value.06.body":
      "Diseñamos alrededor de la realidad de producción: poco tiempo, prioridades cambiantes y límites de assets, sin bajar el estándar.",
    "form_page.title": "Potencia tu marketing\ncon un plan que funciona",
    "form_page.subtitle":
      "Te ayudamos a aclarar objetivos, elegir formatos de promoción y volver con un plan claro, incluso si no sabes por dónde empezar.",
    "form_page.bullet.01": "Alinear con tus objetivos",
    "form_page.bullet.02": "Descubrir formatos que rinden",
    "form_page.bullet.03": "Recibir una propuesta clara y accionable",
    "work_with_us_form.field_full_name": "Nombre y apellidos*",
    "work_with_us_form.field_company": "Nombre de la empresa*",
    "work_with_us_form.field_email": "tu@empresa.com*",
    "work_with_us_form.field_message": "Cuéntanos sobre tu juego o en qué necesitas ayuda...",
    "work_with_us_form.subscribe": "Me gustaría recibir consejos de marketing de vez en cuando",
    "work_with_us_form.submit_sending": "Enviando...",
    "work_with_us_form.submit": "Hablemos",
    "work_with_us_form.privacy_note": "Nunca compartiremos tu información. Solo un experto se pondrá en contacto contigo.",
    "work_with_us_form.success": "¡Gracias! Te contactaremos pronto.",
    "work_with_us_form.error_generic": "Algo salió mal. Inténtalo de nuevo.",
    "work_with_us_form.error_network": "No se pudo enviar. Inténtalo de nuevo.",
    "form.get_a_quote.title": "SOLICITAR PRESUPUESTO",
    "form.get_a_quote.subtitle":
      "Hablemos de tu tarea, y luego iremos a afinar detalles y volveremos con una oferta final.",
    "form.get_a_quote.message_whatsapp": "Enviar mensaje por WhatsApp",
    "form.get_a_quote.card_title": "Trabajemos juntos",
    "form.get_a_quote.field_name": "Nombre*",
    "form.get_a_quote.field_company": "Nombre de la empresa*",
    "form.get_a_quote.field_email": "Correo de trabajo*",
    "form.get_a_quote.submit_sending": "Enviando...",
    "form.get_a_quote.submit_send": "Enviar",
    "form.get_a_quote.success": "¡Gracias! Te contactaremos pronto.",
    "form.get_a_quote.error_generic": "Algo salió mal. Inténtalo de nuevo.",
    "form.get_a_quote.error_network": "No se pudo enviar. Inténtalo de nuevo.",
    "blog_quote_banner.banner.title": "¿Necesitas ayuda con tu plan de marketing para tu juego?",
    "blog_quote_banner.banner.subtitle": "Envía una solicitud rápida y te responderemos con los siguientes pasos",
    "blog_quote_banner.banner.cta": "Pedir presupuesto",
    "blog_quote_banner.modal.title": "Trabajemos juntos",
    "blog_quote_banner.modal.subtitle": "Comparte tus datos y nos pondremos en contacto",
    "blog_quote_banner.modal.close": "Cerrar",
    "blog_quote_banner.success": "¡Gracias! Te contactaremos pronto.",
    "blog_quote_banner.error_generic": "Algo salió mal. Inténtalo de nuevo.",
    "blog_quote_banner.error_network": "No se pudo enviar. Inténtalo de nuevo.",
    "no_wishlists.ui.title": "Sin wishlists en Steam",
    "no_wishlists.ui.subtitle": "Una página práctica y breve que puedes compartir. Sin embeds externos ni contenido CDN.",
    "no_wishlists.ui.reasons.title": "Razones comunes",
    "no_wishlists.ui.reasons.body": "El bajo crecimiento de wishlists suele ser un problema de conversión, no de tráfico. La promesa de la página de la tienda puede no ser clara, la cápsula puede no generar clics, o la página no coincide con el tráfico que estás enviando.",
    "no_wishlists.ui.fix.title": "Qué arreglar primero",
    "no_wishlists.ui.fix.body": "Empieza con el posicionamiento, la claridad de la cápsula y el tráiler corto, luego mejora la parte superior de la página (primer scroll) y valida con un seguimiento limpio.",
    "no_wishlists.ui.tools.title": "Herramientas útiles",
    "no_wishlists.ui.tools.body": "Usa nuestra calculadora para establecer objetivos realistas y verificar tu velocidad actual.",
    "no_wishlists.ui.tools.cta": "Calculadora de Wishlists de Steam",
    "our_cases.ui.title": "Nuestros casos",
    "our_cases.ui.subtitle": "Una selección de resultados. Compartimos lo útil públicamente y mantenemos los detalles sensibles en privado.",
    "our_cases.ui.view_case_study": "Ver caso de estudio",
    "our_cases.ui.next_step": "SIGUIENTE PASO",
    "our_cases.ui.next_step_title": "¿Quieres un resultado similar?",
    "our_cases.ui.next_step_body": "Comparte tu cronograma y objetivos. Te propondremos un plan repetible y mostraremos ejemplos relevantes.",
    "our_cases.ui.contact_us": "Contáctanos",
    "studios_cases.ui.back_to_cases": "← Volver a casos",
    "studios_cases.ui.case_snapshot": "RESUMEN DEL CASO",
    "studios_cases.ui.client": "Cliente",
    "studios_cases.ui.date": "Fecha",
    "studios_cases.ui.note": "Nota",
    "studios_cases.ui.note_body": "Esta página se almacena en el repositorio y no carga contenido externo.",
    "studios_cases.ui.work_with_us": "Trabaja con nosotros",
    "studios_cases.ui.next_step": "SIGUIENTE PASO",
    "studios_cases.ui.next_step_title": "¿Quieres un resultado similar?",
    "studios_cases.ui.next_step_body": "Comparte tu etapa actual y limitaciones. Te propondremos un plan repetible.",
    "studios_cases.ui.contact_us": "Contáctanos",
    "studios_cases.ui.summary": "Resumen",
    "studios_cases.ui.no_sections": "Este caso aún no tiene secciones detalladas.",
    "blog.ui.sidebar_title": "Trap Plan\nBlog",
    "blog.ui.sidebar_subtitle": "Notas, guías y sistemas prácticos de marketing para juegos.",
    "blog.ui.sidebar_latest": "Últimos",
    "blog.ui.sidebar_all": "Todos",
    "pr_starter_pack.ui.hero.body_connector_1": ". Un buen artículo funciona como un",
    "pr_starter_pack.ui.hero.body_connector_2": "y empuja a más jugadores a dar",
    "blog.masterclass.s01.title": 'Steam Next Fest: Miles de juegos competirán, pero ¿cómo obtienes resultados?',
    "blog.masterclass.s01.p01": 'Steam Next Fest ya no es un lugar donde basta con aparecer. Con miles de demos compitiendo al mismo tiempo, la plataforma recompensará los proyectos que lleguen preparados y castigará los que traten el festival como punto de partida. Esta guía explica qué importa realmente en 2026, qué señales observa Steam y cómo convertir la semana en impulso medible.',
    "blog.masterclass.s02.title": 'El Fest de febrero está a la vuelta de la esquina y acabo de terminar mi demo. ¿Debería participar ahora?',
    "blog.masterclass.s02.p01": 'Jordan advierte que Next Fest ya no es la "bala mágica" que fue en 2023 cuando participaban menos de 1.000 juegos. Hoy, con más de 3.000 juegos compitiendo regularmente, el entorno es mucho menos indulgente.',
    "blog.masterclass.s02.p02": 'Si usas el festival como forma de empezar tu marketing desde cero, probablemente estés cometiendo un error. La estrategia ideal es lanzar tu demo al menos unos meses antes del evento para corregir bugs y generar tracción inicial.',
    "blog.masterclass.s02.p03": 'Los juegos que entran a Next Fest con una base sustancial de wishlists actúan como multiplicador del impulso existente, mientras que los que empiezan en frío suelen quedar enterrados por el algoritmo.',
    "blog.masterclass.s03.title": 'Dicen que los livestreams ya no funcionan. ¿Puedo saltarme la transmisión?',
    "blog.masterclass.s03.p01": 'El panorama ha cambiado: Steam ha restado prioridad a los livestreams y ya no proporcionan el enorme impulso de visibilidad que tenían antes. Sin embargo, esto no es razón para saltarlos por completo, ya que la sección dedicada a transmisiones activas sigue existiendo y ofrece una capa de descubrimiento.',
    "blog.masterclass.s03.p02": 'En lugar de agotarte con sesiones en vivo de 10 horas, usa herramientas como Robostreamer para reproducir en bucle material de gameplay de alta calidad o, mejor aún, un influencer conocido jugando tu juego. Esto te permite mantener presencia en la rotación sin agotar recursos que se gastan mejor interactuando con tu comunidad en Discord.',
    "blog.masterclass.s04.title": 'El algoritmo de Steam cambió a finales de 2024. ¿Qué necesito saber sobre las primeras 48 horas?',
    "blog.masterclass.s04.p01": 'Esta es una ventana crítica: durante los dos primeros días del festival, todos los juegos reciben visibilidad aproximadamente igual porque las listas se ordenan aleatoriamente.',
    "blog.masterclass.s04.p02": 'Sin embargo, después de esas 48 horas, Steam cambia a modelos de aprendizaje automático que personalizan el feed para cada usuario según sus intereses específicos y lo que juegan sus amigos.',
    "blog.masterclass.s04.p03": 'Los datos de interacción que Steam recopila durante esos dos primeros días —clics, descargas e interacciones— forman la base de cómo el algoritmo categoriza y recomienda tu juego durante el resto de la semana. Esencialmente, las primeras 48 horas "entrenan" al sistema sobre quién es tu audiencia.',
    "blog.masterclass.s05.title": '¿Steam realmente rastrea si la gente termina mi demo?',
    "blog.masterclass.s05.p01": 'Sorprendentemente, no. En sesiones oficiales de preguntas y respuestas, Valve declaró que las tasas de finalización de demos y el tiempo total de juego no son señales decisivas para la visibilidad post-fest. Creen que sería injusto juzgar una experiencia narrativa de 20 minutos contra un roguelike que se puede jugar eternamente.',
    "blog.masterclass.s05.p02": 'En cambio, Steam se enfoca en "señales de interacción": cuántas personas visitaron tu página de tienda, descargaron la demo y, lo más importante, cuántas añadieron a wishlists o siguieron tu proyecto.',
    "blog.masterclass.s05.p03": 'Enfócate en la conversión —convertir un clic en un wishlist— en lugar de intentar forzar a los jugadores a quedarse en la demo durante horas.',
    "blog.masterclass.s06.title": '¿Por qué usar una página separada para la demo si puedo simplemente añadir un botón a la página principal?',
    "blog.masterclass.s06.p01": 'Una página de demo separada es tu herramienta principal para construir prueba social. Te permite recopilar reseñas específicas para la demo, lo cual es una señal poderosa. Si obtienes muchas reseñas positivas, puede ayudarte a aparecer en las listas de "Tendencia Gratis", trayendo una ola masiva de nuevo tráfico.',
    "blog.masterclass.s06.p02": 'Por el contrario, si la demo recibe comentarios negativos, simplemente puedes eliminar la página separada sin afectar la reputación de tu página principal de tienda.',
    "blog.masterclass.s06.p03": 'Es una forma segura de probar la preparación de tu producto para el mercado, y si aún estás nervioso, usa primero las herramientas de Steam Playtest, donde los comentarios permanecen privados.',
    "blog.masterclass.s07.title": 'Envié emails a influencers el día antes del fest. ¿Por qué nadie responde?',
    "blog.masterclass.s07.p01": 'Probablemente llegaste tarde. El trabajo efectivo de PR con prensa y creadores debe comenzar al menos un mes antes. Tu primer contacto debería ocurrir cuatro semanas antes del inicio, ofreciendo una key con una fecha de embargo clara para que los creadores tengan tiempo de programar su contenido.',
    "blog.masterclass.s07.p02": 'Haz un seguimiento con un recordatorio una semana antes del evento y un "empujón" final el día de apertura.',
    "blog.masterclass.s07.p03": 'No hagas spam a todos; construye una lista curada de creadores de nicho que genuinamente disfruten tu género. Recuerda que más de tres emails suelen cruzar la línea hacia la molestia y pueden dañar tu reputación a largo plazo.',
    "blog.masterclass.s08.title": '¿Cómo hago que los jugadores vuelvan el segundo o tercer día del festival?',
    "blog.masterclass.s08.p01": 'Usa tácticas de "retención a través del engagement" para mantener activa a tu comunidad. Tiny Glade lo hizo brillantemente ofreciendo temas de construcción diarios, mientras que Tears of Metal introdujo modificadores de gameplay diarios para mantener la experiencia fresca.',
    "blog.masterclass.s08.p02": 'Puedes desbloquear recompensas cosméticas exclusivas para el juego completo si los jugadores completan la demo durante ventanas específicas, u organizar devlogs diarios con adelantos de próximas características.',
    "blog.masterclass.s08.p03": 'Uno de los movimientos más poderosos es aprovechar el FOMO ofreciendo una recompensa única por jugar dentro de las primeras 24 horas, asegurando un alto rendimiento durante esa ventana crítica de recopilación de datos de 48 horas.',
    "blog.masterclass.s09.title": 'Mi juego tiene bugs, pero ¿debería seguir desarrollando nuevas funciones durante el fest?',
    "blog.masterclass.s09.p01": 'Olvídate de nuevas funciones durante la semana del festival. Tu único trabajo ahora es "apagar incendios". Está disponible 24/7 para corregir bugs críticos inmediatamente y responder a los comentarios.',
    "blog.masterclass.s09.p02": 'Una respuesta rápida de un desarrollador es la mejor manera de convertir a un jugador frustrado en un fan apasionado. Si ignoras los reportes de bugs durante Next Fest, pierdes la buena voluntad del jugador que no se puede recuperar con ninguna cantidad de publicidad.',
    "blog.masterclass.s09.p03": 'Configura herramientas automatizadas de reporte de bugs directamente en tu menú principal o pantalla de pausa para que los jugadores puedan contactarte al instante en lugar de dejar una reseña negativa.',
    "blog.masterclass.s10.title": 'Escuché sobre "logros" en demos. ¿Es realmente una buena idea?',
    "blog.masterclass.s10.p01": 'No es solo una buena idea; es una necesidad para el engagement. Añadir Logros de Steam a tu demo es una forma probada de motivar a los jugadores.',
    "blog.masterclass.s10.p02": 'Incluye un logro fácil en los primeros 15 minutos para "enganchar" al jugador y mostrarle que las recompensas son alcanzables. Añade otro por completar la demo como incentivo final para terminar la experiencia.',
    "blog.masterclass.s10.p03": 'Una mezcla de logros divertidos y difíciles convierte una simple demo en un desafío gratificante, lo cual se correlaciona directamente con el deseo del jugador de llevar ese progreso al juego completo añadiéndolo a wishlists.',
    "blog.masterclass.s11.title": '¿Por qué no debería lanzar mi juego inmediatamente después de que termine el festival?',
    "blog.masterclass.s11.p01": 'Es una trampa común: el deseo de "golpear mientras el hierro está caliente" lleva a muchos desarrolladores a lanzar exactamente al mismo tiempo que cientos de otros participantes de Next Fest.',
    "blog.masterclass.s11.p02": 'Durante esta ventana, la competencia por un lugar en "Nuevos y Tendencia" es anormalmente alta, y corres el riesgo de ser desplazado por estudios más grandes con presupuestos mayores.',
    "blog.masterclass.s11.p03": 'A menos que tengas al menos 20.000 wishlists y estés seguro de que fuiste uno de los mejores del fest, a menudo es mejor esperar. Deja que el mercado se enfríe, sigue actualizando tu demo y mantén la conexión con tu nueva audiencia para una ventana de lanzamiento más estable.',
};

export default translations;
