import type { CopyKey } from "@/lib/copy";

const translations: Partial<Record<CopyKey, string>> = {
    "nav.about_us": "À propos",
    "nav.services": "Services",
    "nav.our_cases": "Réalisations",
    "nav.blog": "Blog",
    "cta.work_with_us": "Travailler avec nous",
    "cta.read_the_blog": "Lire le blog",
    "cta.lets_talk": "On en parle",
    "hero.badge.01": "Marketing à la performance",
    "hero.badge.02": "Réseaux sociaux",
    "hero.badge.03": "Stratégie go-to-market",
    "hero.kicker": "Marketing pour jeux vidéo",
    "hero.subhead":
      "Nous aidons les studios, éditeurs et équipes indé à lancer, faire grandir et scaler leurs jeux avec un marketing soigné et orienté performance.",
    "hero.body":
      "Stratégie d’abord, exécution ensuite — pensée pour Steam et les contraintes réelles de production.",
    "hero.cta_contact": "Nous contacter",
    "cases.title": "Études de cas",
    "cases.subtitle": "De vraies campagnes pour de vrais jeux.",
    "cases.cta_view_case": "Voir l’étude de cas",
    "cases.cta_view_all": "Voir toutes les études de cas",
    "cases.fallback_metric": "Étude de cas",
    "cases.metric.war_thunder_youtube_europe": "1M+ de vues par mois",
    "cases.metric.enlisted_twitch_ads": "1 500+ nouveaux joueurs atteints",
    "cases.metric.crossout_new_players": "Portée accrue en Europe et aux États-Unis",
    "cases.metric.war_thunder_performance_based": "Activations mensuelles avec KPIs",
    "cases.metric.world_of_tanks_usa": "Campagnes USA avec livraison structurée",
    "cases.metric.brief_for_youtube_twitch": "Briefs clairs + système d’exécution",
    "cases.result.enlisted_twitch_ads": "1 500+ nouveaux joueurs atteints",
    "cases.result.crossout_new_players": "Portée accrue en Europe et aux États-Unis",
    "cases.result.war_thunder_performance_based": "Activations mensuelles avec KPIs",
    "cases.result.world_of_tanks_usa": "Campagnes USA avec livraison structurée",
    "cases.result.brief_for_youtube_twitch": "Briefs clairs + système d’exécution",
    "cases.result.war_thunder_youtube_europe": "1M+ de vues par mois",
    "cases.desc_override.war_thunder_youtube_europe":
      "Campagnes YouTube Ads pour War Thunder dépassant 1 000 000 de vues par mois sur des régions clés en Europe.",
    "services.title": "Services globaux",
    "services.subtitle":
      "Des systèmes complets, de bout en bout, pour des résultats prévisibles — pas des missions ponctuelles.",
    "services.panel.blueprint.title": "Plan de lancement",
    "services.panel.blueprint.desc":
      "Positionnement, messages, planning et mix de canaux. Un plan clair qui réduit le chaos, aligne l’équipe et rend l’exécution prévisible.",
    "services.panel.blueprint.ghost": "STRATÉGIE / MESSAGES / EXÉCUTION",
    "services.panel.paid_growth.title": "Croissance payante",
    "services.panel.paid_growth.desc":
      "Nous configurons les campagnes payantes correctement : choix des canaux, tracking, ciblage et structure. Contrôle, mesure, transfert propre.",
    "services.panel.paid_growth.ghost": "ACQUISITION / ANALYTICS / SCALE",
    "services.panel.creative.title": "Pipeline créatif",
    "services.panel.creative.desc":
      "Un pipeline régulier pour trailers, shortform et assets de store. Pensé pour la vitesse, l’itération et une distribution native.",
    "services.panel.creative.ghost": "PRODUCTION | ADAPTATION | PERFORMANCE",
    "services.mobile_hint": "Touchez pour explorer",
    "packages.title": "Packages prêts à l’emploi",
    "packages.price_label": "Prix :",
    "packages.cta_learn_more": "En savoir plus",
    "packages.media_video_label": "Vidéo",
    "packages.card.reddit.title": "Support de lancement\nReddit",
    "packages.card.reddit.desc":
      "Nous gérons la présence de votre studio sur Reddit depuis son compte officiel. 15 publications ciblées dans les bons subreddits, rédigées pour chaque communauté et générer des wishlists.",
    "packages.card.pr_starter.title": "Pack PR Starter",
    "packages.card.pr_starter.desc":
      "PR pour obtenir de la couverture : communiqué de presse lisible, pitches ciblés, relances, et liste complète de contacts. Conçu pour la crédibilité et les wishlists Steam.",
    "packages.card.influencer_micro.title": "Micro-campagne\ninfluenceurs",
    "packages.card.influencer_micro.desc":
      "Nous identifions des créateurs de niche, coordonnons les activations et suivons la performance. Rentable, scalable et axé sur une portée de qualité.",
    "packages.card.tiktok_20.title": "Pack TikTok :\n20 vidéos",
    "packages.card.tiktok_20.desc":
      "20 vidéos TikTok sur mesure pour votre jeu. Concept, production et format : nous gérons tout, aligné sur les tendances et le comportement de l’audience.",
    "packages.card.paid_ads_setup.title": "Mise en place des ads payantes",
    "packages.card.paid_ads_setup.desc":
      "On met en place vos campagnes payantes de A à Z : choix des canaux, budget, ciblage et placements créatifs. Après lancement, on vous transmet le compte. Pas de suivi/optimisation continue inclus.",
    "packages.card.gameplay_trailer.title": "Trailer de gameplay",
    "packages.card.gameplay_trailer.desc":
      "Un trailer gameplay complet, premium, conçu pour votre jeu. Storytelling clair, capture soignée, rythme, montage et livraison prête pour Steam, YouTube et la distribution média.",
    "seo.site.name": "Marketing de jeux vidéo | Marketing pour jeux indie",
    "seo.site.description": "TrapPlan aide les studios à augmenter les wishlists et les ventes grâce à un marketing orienté performance.",
    "seo.about.title": "À propos | TrapPlan Agence Marketing Jeux Vidéo",
    "seo.about.desc": "TrapPlan aide les studios à augmenter les wishlists et les ventes avec des systèmes marketing orientés performance.",
    "seo.blog.title": "Blog marketing gaming | Tendances & conseils",
    "seo.blog.desc":
      "Restez à jour sur les tendances du marketing d’influence gaming. Le blog TrapPlan partage conseils, études de cas et stratégies pour performer.",
    "seo.our_cases.title": "Nos cas | Résultats et études de cas marketing gaming",
    "seo.our_cases.desc": "Résultats sélectionnés et études de cas de TrapPlan.",
    "seo.no_wishlists.title": "Pas de wishlists sur Steam | Améliorez la conversion de votre page",
    "seo.no_wishlists.desc": "Que faire quand votre page Steam a du trafic mais que les wishlists ne progressent pas.",
    "seo.reddit_launch_support.title": "Support de lancement Reddit : trafic organique sans backlash",
    "seo.reddit_launch_support.desc":
      "Campagne organique Reddit de 15 posts conçue pour augmenter les wishlists Steam sans déclencher le backlash marketing habituel.",
    "seo.pr_starter_pack.title": "Pack PR Starter : la couverture que votre jeu mérite",
    "seo.pr_starter_pack.desc":
      "PR pour indés : communiqué lisible, pitches ciblés, relances et liste de contacts. Pour crédibilité et wishlists Steam.",
    "seo.tiktok_20.title": "Pack TikTok : 20 vidéos pour campagnes marketing gaming",
    "seo.tiktok_20.desc":
      "20 vidéos TikTok sur mesure pour votre jeu : hooks, scripts, montage et plan de contenu conçu pour la notoriété et les wishlists.",
    "seo.influencer_micro.title":
      "Micro-campagne influenceurs : une portée efficiente qui convertit",
    "seo.influencer_micro.desc":
      "Sprint d’activation micro-influenceurs pour jeux : sélection de créateurs de niche, outreach, coordination, tracking et rapport clair. Conçu pour une portée utile et des wishlists Steam.",
    "seo.influencer_activation.title": "Activation d’influenceurs pour jeux : une couverture qui convertit",
    "seo.influencer_activation.desc":
      "Campagnes influenceurs structurées : sourcing, outreach, coordination, tracking et apprentissages post-campagne. Répétable, mesurable et conçu pour les jeux.",
    "seo.paid_ads_setup.title": "Mise en place des ads payantes : lancer correctement",
    "seo.paid_ads_setup.desc":
      "On met en place vos campagnes payantes de A à Z : choix des canaux, budget, ciblage et placements créatifs. Après lancement, on vous transmet le compte. Pas de suivi/optimisation continue inclus.",
    "seo.gameplay_trailer.title": "Trailer de gameplay : un trailer conçu pour convertir",
    "seo.gameplay_trailer.desc":
      "Un trailer gameplay complet conçu pour votre jeu : storytelling, capture soignée, rythme, montage et livraison prête pour Steam, YouTube et la distribution média.",
    "seo.steam_wishlist_calculator.title": "Calculateur de wishlists Steam | Estimez ventes et trafic",
    "seo.steam_wishlist_calculator.desc":
      "Estimez les wishlists, le trafic et le budget nécessaires pour atteindre votre objectif de ventes Steam en semaine 1.",
    "seo.steam_pricing_planner.title": "Planificateur et calculateur de prix Steam | Outil régional",
    "seo.steam_pricing_planner.desc":
      "Calculez des prix régionaux Steam recommandés avec la parité de pouvoir d’achat (PPP) et des taux de change en temps réel.",
    "seo.steam_influencers_planner.title": "Planificateur d’influenceurs Steam | Trouvez des créateurs gaming",
    "seo.steam_influencers_planner.desc":
      "Outil pro pour découvrir des influenceurs gaming YouTube et Twitch selon le genre et des jeux similaires.",
    "seo.steam_festival_planner.title": "Planificateur de festivals Steam | Événements pour votre jeu",
    "seo.steam_festival_planner.desc":
      "Parcourez les festivals et promotions Steam, filtrez par type et genre, et matchez les événements à votre jeu via une analyse AppID.",
    "seo.creative_content_pipeline.title":
      "Pipeline de contenu créatif pour jeux Steam et consoles",
    "seo.creative_content_pipeline.desc":
      "Un pipeline continu pour trailers, shorts, assets de store et production itérative — orienté croissance des wishlists et conversion.",
    "seo.paid_growth.title": "Croissance payante pour jeux Steam et consoles",
    "seo.paid_growth.desc":
      "Croissance payante high-ticket : stratégie de canaux, tracking propre, attribution et transfert structuré.",
    "seo.game_launch_blueprint.title": "Plan de lancement : votre stratégie, nos standards.",
    "seo.game_launch_blueprint.desc":
      "Arrêtez de deviner. Nous fournissons le framework marketing utilisé par les éditeurs : standardisé, éprouvé, et prêt à exécuter ensemble.",
    "seo.games_co_publishing.title": "Co-édition : partenaire marketing & distribution.",
    "seo.games_co_publishing.desc":
      "Partenariat de co-édition guidé par le marketing : visibilité, validation de marché, croissance d’audience et performance commerciale.",
    "seo.blog.masterclass.title": "Steam Next Fest : la masterclass de la découverte",
    "seo.blog.masterclass.desc":
      "Une analyse approfondie (2026) de Steam Next Fest : ce qui compte aujourd’hui, les 48 premières heures, les signaux de conversion, la stratégie de page de démo, le timing influenceurs et comment passer du conseil à l’exécution.",
    "legal.content_rules.meta_title": "Règles de contenu | Directives d'utilisation TrapPlan",
    "legal.content_rules.meta_desc": "Règles de base pour utiliser le contenu et les ressources TrapPlan.",
    "legal.copyright.meta_title": "Politique de copyright | Propriété intellectuelle TrapPlan",
    "legal.copyright.meta_desc": "Politique de copyright du contenu du site TrapPlan.",
    "form_page.title": "Fais passer ton marketing\nau niveau supérieur",
    "form_page.subtitle":
      "On t’aide à clarifier tes objectifs, choisir les bons formats de promotion et revenir avec un plan clair — même si tu ne sais pas par où commencer.",
    "form_page.bullet.01": "S'aligner sur tes objectifs",
    "form_page.bullet.02": "Découvrir les formats les plus performants",
    "form_page.bullet.03": "Recevoir une proposition claire et actionnable",
    "work_with_us_form.field_full_name": "Nom complet*",
    "work_with_us_form.field_company": "Nom de l'entreprise*",
    "work_with_us_form.field_email": "toi@tonentreprise.com*",
    "work_with_us_form.field_message": "Parle-nous de ton jeu ou de ce dont tu as besoin...",
    "work_with_us_form.subscribe": "Je souhaite recevoir des conseils marketing de temps en temps",
    "work_with_us_form.submit_sending": "Envoi en cours...",
    "work_with_us_form.submit": "Discutons",
    "work_with_us_form.privacy_note": "Nous ne partagerons jamais tes informations. Un seul expert te contactera.",
    "work_with_us_form.success": "Merci ! Nous te contacterons bientôt.",
    "work_with_us_form.error_generic": "Une erreur est survenue. Réessaie.",
    "work_with_us_form.error_network": "Échec de l'envoi. Réessaie.",
    "form.get_a_quote.title": "DEMANDER UN DEVIS",
    "form.get_a_quote.subtitle":
      "Parlons de ta tâche, puis on peaufine et on revient avec une offre finale.",
    "form.get_a_quote.message_whatsapp": "Envoyer un message sur WhatsApp",
    "form.get_a_quote.card_title": "Travaillons ensemble",
    "form.get_a_quote.field_name": "Nom*",
    "form.get_a_quote.field_company": "Nom de l'entreprise*",
    "form.get_a_quote.field_email": "E-mail professionnel*",
    "form.get_a_quote.submit_sending": "Envoi en cours...",
    "form.get_a_quote.submit_send": "Envoyer",
    "form.get_a_quote.success": "Merci ! Nous te contacterons bientôt.",
    "form.get_a_quote.error_generic": "Une erreur est survenue. Réessaie.",
    "form.get_a_quote.error_network": "Échec de l'envoi. Réessaie.",
    "blog_quote_banner.banner.title": "Besoin d’aide pour ton plan marketing de jeu ?",
    "blog_quote_banner.banner.subtitle": "Envoie une demande rapide et nous répondrons avec les prochaines étapes",
    "blog_quote_banner.banner.cta": "Demander un devis",
    "blog_quote_banner.modal.title": "Travaillons ensemble",
    "blog_quote_banner.modal.subtitle": "Partage tes informations et nous te recontacterons",
    "blog_quote_banner.modal.close": "Fermer",
    "blog_quote_banner.success": "Merci ! Nous te contacterons bientôt.",
    "blog_quote_banner.error_generic": "Une erreur est survenue. Réessaie.",
    "blog_quote_banner.error_network": "Échec de l’envoi. Réessaie.",
    "no_wishlists.ui.title": "Pas de wishlists sur Steam",
    "no_wishlists.ui.subtitle": "Une page pratique et concise à partager. Pas d’embeds externes, pas de contenu CDN.",
    "no_wishlists.ui.reasons.title": "Raisons courantes",
    "no_wishlists.ui.reasons.body": "Une faible croissance des wishlists est généralement un problème de conversion, pas de trafic. La promesse de la page du store peut être floue, la capsule peut ne pas générer de clics, ou la page ne correspond pas au trafic que vous envoyez.",
    "no_wishlists.ui.fix.title": "Quoi corriger en premier",
    "no_wishlists.ui.fix.body": "Commencez par le positionnement, la clarté de la capsule et du trailer court, puis améliorez le haut de la page (premier scroll) et validez avec un tracking propre.",
    "no_wishlists.ui.tools.title": "Outils utiles",
    "no_wishlists.ui.tools.body": "Utilisez notre calculateur pour fixer des objectifs réalistes et vérifier votre vélocité actuelle.",
    "no_wishlists.ui.tools.cta": "Calculateur de Wishlists Steam",
    "our_cases.ui.title": "Nos réalisations",
    "our_cases.ui.subtitle": "Une sélection de résultats. Nous partageons ce qui est utile publiquement et gardons les détails sensibles privés.",
    "our_cases.ui.view_case_study": "Voir l’étude de cas",
    "our_cases.ui.next_step": "PROCHAINE ÉTAPE",
    "our_cases.ui.next_step_title": "Vous voulez un résultat similaire ?",
    "our_cases.ui.next_step_body": "Partagez votre calendrier et vos objectifs. Nous proposerons un plan reproductible et montrerons des exemples pertinents.",
    "our_cases.ui.contact_us": "Contactez-nous",
    "studios_cases.ui.back_to_cases": "← Retour aux cas",
    "studios_cases.ui.case_snapshot": "APERÇU DU CAS",
    "studios_cases.ui.client": "Client",
    "studios_cases.ui.date": "Date",
    "studios_cases.ui.note": "Note",
    "studios_cases.ui.note_body": "Cette page est stockée dans le dépôt et ne charge aucun contenu externe.",
    "studios_cases.ui.work_with_us": "Travailler avec nous",
    "studios_cases.ui.next_step": "PROCHAINE ÉTAPE",
    "studios_cases.ui.next_step_title": "Vous voulez un résultat similaire ?",
    "studios_cases.ui.next_step_body": "Partagez votre étape actuelle et vos contraintes. Nous proposerons un plan reproductible.",
    "studios_cases.ui.contact_us": "Contactez-nous",
    "studios_cases.ui.summary": "Résumé",
    "studios_cases.ui.no_sections": "Ce cas n’a pas encore de sections détaillées.",
    "blog.ui.sidebar_title": "Trap Plan\nBlog",
    "blog.ui.sidebar_subtitle": "Notes, guides et systèmes pratiques de marketing pour jeux vidéo.",
    "blog.ui.sidebar_latest": "Récents",
    "blog.ui.sidebar_all": "Tous",
    "pr_starter_pack.ui.hero.body_connector_1": ". Un bon article fonctionne comme un",
    "pr_starter_pack.ui.hero.body_connector_2": "et pousse plus de joueurs à cliquer sur",
    "blog.masterclass.s01.title": 'Steam Next Fest : Des milliers de jeux seront en compétition, mais comment obtenir des résultats ?',
    "blog.masterclass.s01.p01": 'Steam Next Fest n’est plus un endroit où il suffit de se montrer. Avec des milliers de démos en compétition simultanément, la plateforme récompensera les projets préparés et pénalisera ceux qui traitent le festival comme un point de départ. Ce guide explique ce qui compte vraiment en 2026, quels signaux Steam observe et comment transformer la semaine en élan mesurable.',
    "blog.masterclass.s02.title": 'Le Fest de février approche et je viens de finir ma démo. Dois-je me lancer maintenant ?',
    "blog.masterclass.s02.p01": 'Jordan prévient que Next Fest n’est plus la « balle magique » de 2023 quand moins de 1 000 jeux participaient. Aujourd’hui, avec plus de 3 000 jeux en compétition régulière, l’environnement est bien moins indulgent.',
    "blog.masterclass.s02.p02": 'Si tu utilises le festival pour démarrer ton marketing de zéro, tu fais probablement une erreur. La stratégie idéale est de lancer ta démo au moins quelques mois avant l’événement pour corriger les bugs et construire une traction initiale.',
    "blog.masterclass.s02.p03": 'Les jeux qui entrent à Next Fest avec une base solide de wishlists agissent comme multiplicateur de l’élan existant, tandis que ceux qui démarrent à froid se retrouvent souvent enterrés par l’algorithme.',
    "blog.masterclass.s03.title": 'On dit que les livestreams ne marchent plus. Puis-je sauter la diffusion ?',
    "blog.masterclass.s03.p01": 'Le paysage a changé : Steam a déprioritisé les livestreams et ils ne fournissent plus l’énorme boost de visibilité d’avant. Cependant, ce n’est pas une raison pour les sauter complètement, car la section dédiée aux diffusions actives existe toujours et offre une couche de découverte.',
    "blog.masterclass.s03.p02": 'Au lieu de t’épuiser avec des sessions live de 10 heures, utilise des outils comme Robostreamer pour diffuser en boucle du gameplay de haute qualité ou, mieux encore, un influenceur connu jouant à ton jeu. Cela te permet de maintenir une présence dans la rotation sans épuiser des ressources mieux employées à interagir avec ta communauté sur Discord.',
    "blog.masterclass.s04.title": 'L’algorithme de Steam a changé fin 2024. Que dois-je savoir sur les 48 premières heures ?',
    "blog.masterclass.s04.p01": 'C’est une fenêtre critique : pendant les deux premiers jours du festival, tous les jeux reçoivent une visibilité à peu près égale car les listes sont triées aléatoirement.',
    "blog.masterclass.s04.p02": 'Cependant, après ces 48 heures, Steam passe à des modèles de machine learning qui personnalisent le feed pour chaque utilisateur en fonction de ses intérêts spécifiques et de ce que jouent ses amis.',
    "blog.masterclass.s04.p03": 'Les données d’interaction que Steam collecte pendant ces deux premiers jours — clics, téléchargements et interactions — forment la base de la façon dont l’algorithme catégorise et recommande ton jeu pour le reste de la semaine. Essentiellement, les 48 premières heures « entraînent » le système sur qui est ton public.',
    "blog.masterclass.s05.title": 'Steam suit-il vraiment si les gens finissent ma démo ?',
    "blog.masterclass.s05.p01": 'Étonnamment, non. Lors de sessions officielles de Q&R, Valve a déclaré que les taux de complétion des démos et le temps de jeu total ne sont pas des signaux décisifs pour la visibilité post-fest. Ils estiment qu’il serait injuste de juger une expérience narrative de 20 minutes face à un roguelike jouable à l’infini.',
    "blog.masterclass.s05.p02": 'Au lieu de cela, Steam se concentre sur les « signaux d’interaction » : combien de personnes ont visité ta page de store, téléchargé la démo et, surtout, combien ont ajouté à leur wishlist ou suivi ton projet.',
    "blog.masterclass.s05.p03": 'Concentre-toi sur la conversion — transformer un clic en wishlist — plutôt que d’essayer de forcer les joueurs à rester dans la démo pendant des heures.',
    "blog.masterclass.s06.title": 'Pourquoi utiliser une page séparée pour la démo si je peux simplement ajouter un bouton à la page principale ?',
    "blog.masterclass.s06.p01": 'Une page démo séparée est ton outil principal pour construire la preuve sociale. Elle te permet de collecter des avis spécifiques pour la démo, ce qui est un signal puissant. Si tu obtiens beaucoup d’avis positifs, cela peut t’aider à apparaître dans les classements « Tendance Gratuit », apportant une vague massive de nouveau trafic.',
    "blog.masterclass.s06.p02": 'Inversement, si la démo reçoit des retours négatifs, tu peux simplement retirer la page séparée sans affecter la réputation de ta page principale de store.',
    "blog.masterclass.s06.p03": 'C’est un moyen sûr de tester la préparation de ton produit pour le marché, et si tu es encore nerveux, utilise d’abord les outils Steam Playtest, où les retours restent privés.',
    "blog.masterclass.s07.title": 'J’ai envoyé des emails aux influenceurs la veille du fest. Pourquoi personne ne répond ?',
    "blog.masterclass.s07.p01": 'Tu es probablement en retard. Le travail PR efficace avec la presse et les créateurs doit commencer au moins un mois à l’avance. Ton premier contact devrait avoir lieu quatre semaines avant le début, en offrant une clé avec une date d’embargo claire pour que les créateurs aient le temps de planifier leur contenu.',
    "blog.masterclass.s07.p02": 'Fais un suivi avec un rappel une semaine avant l’événement et une dernière « poussée » le jour d’ouverture.',
    "blog.masterclass.s07.p03": 'Ne spamme pas tout le monde ; construis une liste curatrice de créateurs de niche qui apprécient sincèrement ton genre. Rappelle-toi que plus de trois emails franchissent généralement la limite de l’agacement et peuvent nuire à ta réputation à long terme.',
    "blog.masterclass.s08.title": 'Comment faire revenir les joueurs le deuxième ou troisième jour du festival ?',
    "blog.masterclass.s08.p01": 'Utilise des tactiques de « rétention par l’engagement » pour garder ta communauté active. Tiny Glade l’a fait brillamment en proposant des thèmes de construction quotidiens, tandis que Tears of Metal a introduit des modificateurs de gameplay quotidiens pour garder l’expérience fraîche.',
    "blog.masterclass.s08.p02": 'Tu peux débloquer des récompenses cosmétiques exclusives pour le jeu complet si les joueurs terminent la démo pendant des fenêtres spécifiques, ou organiser des devlogs quotidiens avec des aperçus des prochaines fonctionnalités.',
    "blog.masterclass.s08.p03": 'L’un des mouvements les plus puissants est d’exploiter le FOMO en offrant une récompense unique pour jouer dans les 24 premières heures, assurant de hautes performances pendant cette fenêtre critique de collecte de données de 48 heures.',
    "blog.masterclass.s09.title": 'Mon jeu a des bugs, mais dois-je continuer à développer de nouvelles fonctionnalités pendant le fest ?',
    "blog.masterclass.s09.p01": 'Oublie les nouvelles fonctionnalités pendant la semaine du festival. Ton seul travail maintenant est de « combattre les incendies ». Sois disponible 24h/24 pour corriger immédiatement les bugs critiques et répondre aux retours.',
    "blog.masterclass.s09.p02": 'Une réponse rapide d’un développeur est le meilleur moyen de transformer un joueur frustré en fan passionné. Si tu ignores les rapports de bugs pendant Next Fest, tu perds la bonne volonté des joueurs qui ne peut être rachetée par aucune quantité de publicité.',
    "blog.masterclass.s09.p03": 'Configure des outils automatisés de signalement de bugs directement dans ton menu principal ou écran de pause pour que les joueurs puissent te contacter instantanément au lieu de laisser un avis négatif.',
    "blog.masterclass.s10.title": 'J’ai entendu parler des « succès » dans les démos. Est-ce vraiment une bonne idée ?',
    "blog.masterclass.s10.p01": 'Ce n’est pas seulement une bonne idée ; c’est une nécessité pour l’engagement. Ajouter des Succès Steam à ta démo est un moyen prouvé de motiver les joueurs.',
    "blog.masterclass.s10.p02": 'Inclus un succès facile dans les 15 premières minutes pour « accrocher » le joueur et lui montrer que les récompenses sont atteignables. Ajoutes-en un autre pour compléter la démo comme incitation finale à finir l’expérience.',
    "blog.masterclass.s10.p03": 'Un mélange de succès amusants et difficiles transforme une simple démo en un défi gratifiant, ce qui est directement corrélé avec le désir du joueur de transférer cette progression dans le jeu complet en l’ajoutant à sa wishlist.',
    "blog.masterclass.s11.title": 'Pourquoi ne devrais-je pas lancer mon jeu immédiatement après la fin du festival ?',
    "blog.masterclass.s11.p01": 'C’est un piège courant : le désir de « battre le fer tant qu’il est chaud » pousse de nombreux développeurs à lancer exactement en même temps que des centaines d’autres participants de Next Fest.',
    "blog.masterclass.s11.p02": 'Pendant cette fenêtre, la compétition pour une place dans « Nouveaux et Tendance » est anormalement élevée, et tu risques d’être repoussé par des studios plus grands avec des budgets plus importants.',
    "blog.masterclass.s11.p03": 'Sauf si tu as au moins 20 000 wishlists et que tu es sûr d’avoir été l’un des meilleurs du fest, il est souvent préférable d’attendre. Laisse le marché se refroidir, continue à mettre à jour ta démo et maintiens la connexion avec ton nouveau public pour une fenêtre de lancement plus stable.',
    // ===== REDESIGN 2026 (dark theme) =====
    "hero.title_l1": "Le marketing des jeux,",
    "hero.title_l2_pre": "pensé pour ",
    "hero.title_accent": "les réalités de Steam.",
    "hero.cta_cases": "Voir les études de cas",
    "trusted.label": "La confiance des studios qui sortent sur toutes les plateformes",
    "services.eyebrow": "Ce que nous faisons",
    "services.global_title": "Services globaux",
    "services.global_subtitle": "Des systèmes plus poussés, de bout en bout, pour les studios qui veulent des résultats prévisibles — pas des tâches isolées.",
    "services.row.blueprint.title": "Plan de lancement de jeu",
    "services.row.blueprint.sub": "Stratégie · Messages · Exécution",
    "services.row.blueprint.body": "Positionnement, messages, calendrier et mix de canaux. Un plan clair qui élimine le chaos, aligne l’équipe et rend l’exécution prévisible.",
    "services.row.blueprint.tags": "Positionnement|Calendrier de lancement|Mix de canaux",
    "services.row.paid.title": "Croissance payante",
    "services.row.paid.sub": "Acquisition · Analytique · Échelle",
    "services.row.paid.body": "Des campagnes payantes configurées comme il faut : choix des canaux, suivi, ciblage et structure. Conçues pour le contrôle, la mesure et une transmission propre.",
    "services.row.paid.tags": "Choix des canaux|Suivi & ciblage|Transmission propre",
    "services.row.organic.title": "Croissance organique",
    "services.row.organic.sub": "Reddit · Communauté · Wishlists",
    "services.row.organic.body": "Une dynamique de wishlists durable sans dépendre des dépenses publicitaires — présence sur Reddit, amorçage de communauté et contenu court organique qui se renforce avec le temps.",
    "services.row.organic.tags": "Reddit|Communauté|Vélocité des wishlists",
    "publishing.promo.eyebrow": "Également signé TrapPlan",
    "publishing.promo.title_l1": "Nous ne faisons pas que le marketing des jeux.",
    "publishing.promo.title_l2_pre": "Nous les ",
    "publishing.promo.title_accent": "éditons",
    "publishing.promo.title_l2_post": ".",
    "publishing.promo.body_pre": "Un partenariat d’édition sélectif — financement, soutien à la production et un lancement complet. Vous gardez votre jeu et ",
    "publishing.promo.body_ip": "100% de votre IP",
    "publishing.promo.cta": "Découvrir Trap Plan Publishing",
    "publishing.promo.row1.title": "Tests marketing",
    "publishing.promo.row1.desc": " · validez vos accroches avant de monter en dépenses",
    "publishing.promo.row2.title": "Soutien à la production",
    "publishing.promo.row2.desc": " · QA et assets de boutique, avec vous",
    "publishing.promo.row3.title": "Go-to-market complet",
    "publishing.promo.row3.desc": " · wishlists, créateurs, PR, payant",
    "publishing.promo.row4.title": "Distribution & long terme",
    "publishing.promo.row4.desc": " · croissance et expansion sur les plateformes",
    "cases.eyebrow": "Études de cas",
    "cases.read_case": "Lire l’étude",
    "cases.view_all_tile_sub": "Wargaming · Gaijin",
    "cases.catalog.sub": "De vraies campagnes, de vrais jeux",
    "cases.filter.all": "Tous les cas",
    "cases.filter.wargaming": "Wargaming",
    "cases.filter.gaijin": "Gaijin",
    "packages.eyebrow": "Packages prêts à l’emploi",
    "packages.home_title": "Des packages à prix fixe",
    "packages.home_subtitle": "Cadrés, chiffrés et prêts à démarrer. Choisissez une option ou combinez-les — aucun appel de cadrage requis.",
    "form.get_a_quote.eyebrow": "Demander un devis",
    "form.get_a_quote.field_budget": "Budget",
    "form.get_a_quote.budget_placeholder": "Sélectionnez une fourchette",
    "form.get_a_quote.field_message": "Parlez-nous de votre jeu",
    "form.get_a_quote.footnote": "Nous répondons sous un jour ouvré. Jamais de spam.",
    "nav.why_us": "Pourquoi nous",
    "nav.how_we_help": "Comment nous aidons",
    "nav.your_ip": "Votre IP",
    "nav.agency": "Agence",
    "cta.submit_game": "Soumettez votre jeu",
    "publishing.hero.badge": "Candidatures désormais ouvertes",
    "publishing.hero.title_l1": "Nous éditons les jeux",
    "publishing.hero.title_l2_pre": "auxquels nous ",
    "publishing.hero.title_accent": "croyons",
    "publishing.hero.title_l2_post": ".",
    "publishing.hero.lede": "Financement, une équipe marketing senior et un lancement complet — pour un petit nombre de jeux chaque année. Vous gardez 100% de votre IP. Nous gagnons quand vous gagnez.",
    "publishing.marquee": "Financement|Marketing|Créateurs|PR|Portage|Localisation|QA|Boutique",
    "publishing.value1.title": "La performance d’abord",
    "publishing.value1.body": "Nous investissons dans le marketing avec confiance dans le résultat. Chaque euro est lié aux wishlists, aux installations et aux ventes — mesuré, pas espéré.",
    "publishing.value2.title": "Sortir moins, sortir mieux",
    "publishing.value2.body": "Nous prenons une poignée de jeux par an et plaçons une vraie équipe derrière chacun. Nous n’éditons que des jeux auxquels nous croyons sincèrement — et les soutenons comme il faut.",
    "publishing.ip.eyebrow": "Aucune mainmise sur l’IP · jamais",
    "publishing.ip.title": "Vous gardez 100% de votre IP.",
    "publishing.ip.body": "Nous finançons et éditons — vous restez propriétaire. Pas de rachats, pas de clauses pièges, pas de petites lignes. Votre jeu, vos personnages et votre marque restent entièrement à vous.",
    "publishing.how.title": "Une équipe complète sur tout le lancement.",
    "publishing.how.card1.title": "Marketing disruptif",
    "publishing.how.card1.body": "Des campagnes rentables qui créent une vraie notoriété auprès des joueurs — pour que vous puissiez vous concentrer sur le jeu.",
    "publishing.how.card1.tags": "Stratégie & plan|Créateurs|PR",
    "publishing.how.card2.title": "Édition stratégique",
    "publishing.how.card2.body": "Financement et planification du cycle de vie qui maximisent les revenus sur chaque plateforme et chaque boutique.",
    "publishing.how.card2.tags": "Relations plateformes|Boutique|Portage|Localisation",
    "publishing.how.card3.title": "Soutien complet",
    "publishing.how.card3.body": "Une équipe aux côtés de la vôtre — QA, retours de design et partenaires pour le contenu qui fait décoller le jeu.",
    "publishing.how.card3.tags": "QA & retours|Bande-son|Art & cinématiques",
    "publishing.how.card4.title": "Financement & ressources",
    "publishing.how.card4.body": "Du capital pour finir et lancer — investi là où il fait vraiment bouger les wishlists, les installations et les ventes.",
    "publishing.how.card4.tags": "Financement dev|Budget de lancement|Dépenses marketing",
    "publishing.compare.eyebrow": "Agence ou édition ?",
    "publishing.compare.title": "Deux façons de travailler avec nous.",
    "publishing.compare.agency.label": "L’agence",
    "publishing.compare.agency.title": "Vous pilotez, nous exécutons",
    "publishing.compare.agency.body": "Des packages et des campagnes cadrés à prix fixe. Vous gardez le contrôle total et démarrez en quelques jours.",
    "publishing.compare.agency.cta": "Voir les packages",
    "publishing.compare.pub.label": "Édition",
    "publishing.compare.pub.title": "Nous nous associons sur tout le jeu",
    "publishing.compare.pub.body": "Financement, production et lancement complet — pour une part des bénéfices, jamais votre IP. Sélectif, sur candidature.",
    "publishing.cta.title": "Vous pensez que votre jeu a sa place ?",
    "publishing.cta.body": "Envoyez-nous le build et la vision. Si ça colle, nous reviendrons avec une vraie offre de partenariat — votre IP reste la vôtre, toujours.",
    "seo.publishing.title": "Trap Plan Publishing — nous éditons les jeux auxquels nous croyons",
    "seo.publishing.description": "Un partenariat d’édition de jeux sélectif : financement, une équipe marketing senior et un lancement complet. Vous gardez 100% de votre IP.",
    "tools.ui.free_tool": "Outil gratuit",
    "tools.ui.free_tool_sub": "Calculs de lancement Steam",
    "tools.cta.title": "Envie d’atteindre vraiment ces chiffres ?",
    "tools.cta.body": "Les calculs sont le point de départ. Nous construisons les campagnes qui font grandir vos wishlists — et les convertissent au lancement.",
    "packages.detail.eyebrow": "Package",
    "packages.detail.fixed_price": "Prix fixe",
    "packages.detail.one_time": "paiement unique",
    "packages.detail.request": "Demander ce package",
    "packages.detail.talk": "Parlons-en d’abord",
    "packages.detail.included_eyebrow": "Ce qui est inclus",
    "packages.detail.process_eyebrow": "Comment ça marche",
    "packages.detail.pairs_well": "S’associe bien avec",
    "packages.detail.all_packages": "Tous les packages",
    "packages.detail.breadcrumb_packages": "Packages",

};

export default translations;
