import type { CopyKey } from "@/lib/copy";

const translations: Partial<Record<CopyKey, string>> = {
    "nav.about_us": "Chi siamo",
    "nav.services": "Servizi",
    "nav.our_cases": "Casi",
    "nav.blog": "Blog",
    "cta.work_with_us": "Lavora con noi",
    "cta.read_the_blog": "Leggi il blog",
    "cta.lets_talk": "Parliamone",
    "hero.badge.01": "Performance marketing",
    "hero.badge.02": "Social media",
    "hero.badge.03": "Strategia go-to-market",
    "hero.kicker": "Marketing per videogiochi",
    "hero.subhead":
      "Aiutiamo studi, publisher e team indie a lanciare, crescere e scalare giochi con marketing curato e orientato ai risultati.",
    "hero.body":
      "Prima la strategia, poi l’esecuzione — pensato per Steam e per i vincoli reali di produzione.",
    "hero.cta_contact": "Contattaci",
    "cases.title": "Case study",
    "cases.subtitle": "Campagne reali per giochi reali.",
    "cases.cta_view_case": "Vedi case study",
    "cases.cta_view_all": "Vedi tutti i case study",
    "cases.fallback_metric": "Case study",
    "cases.metric.war_thunder_youtube_europe": "1M+ visualizzazioni al mese",
    "cases.metric.enlisted_twitch_ads": "Raggiunti 1.500+ nuovi giocatori",
    "cases.metric.crossout_new_players": "Espansione in Europa e USA",
    "cases.metric.war_thunder_performance_based": "Attivazioni mensili con focus KPI",
    "cases.metric.world_of_tanks_usa": "Campagne USA con delivery strutturata",
    "cases.metric.brief_for_youtube_twitch": "Brief chiari e sistema di esecuzione",
    "cases.result.enlisted_twitch_ads": "Raggiunti 1.500+ nuovi giocatori",
    "cases.result.crossout_new_players": "Espansione in Europa e USA",
    "cases.result.war_thunder_performance_based": "Attivazioni mensili con focus KPI",
    "cases.result.world_of_tanks_usa": "Campagne USA con delivery strutturata",
    "cases.result.brief_for_youtube_twitch": "Brief chiari e sistema di esecuzione",
    "cases.result.war_thunder_youtube_europe": "1M+ visualizzazioni al mese",
    "cases.desc_override.war_thunder_youtube_europe":
      "Campagne YouTube Ads per War Thunder con oltre 1.000.000 di visualizzazioni al mese nelle principali aree europee.",
    "services.title": "Servizi globali",
    "services.subtitle":
      "Sistemi end-to-end per studi che vogliono risultati prevedibili — non attività una tantum.",
    "services.panel.blueprint.title": "Blueprint di lancio",
    "services.panel.blueprint.desc":
      "Posizionamento, messaggi, timeline e mix di canali. Un piano chiaro che riduce il caos, allinea il team e rende l’esecuzione prevedibile.",
    "services.panel.blueprint.ghost": "STRATEGIA / MESSAGGI / ESECUZIONE",
    "services.panel.paid_growth.title": "Crescita a pagamento",
    "services.panel.paid_growth.desc":
      "Impostiamo campagne paid nel modo corretto: canali, tracking, targeting e struttura. Controllo, misurazione e handoff pulito.",
    "services.panel.paid_growth.ghost": "ACQUISIZIONE / ANALYTICS / SCALA",
    "services.panel.creative.title": "Pipeline creativa",
    "services.panel.creative.desc":
      "Una pipeline costante per trailer, shortform e asset store. Pensata per velocità, iterazione e distribuzione nativa.",
    "services.panel.creative.ghost": "PRODUZIONE | ADATTAMENTO | PERFORMANCE",
    "services.mobile_hint": "Tocca per esplorare",
    "packages.title": "Pacchetti pronti all’uso",
    "packages.price_label": "Prezzo:",
    "packages.cta_learn_more": "Scopri di più",
    "packages.media_video_label": "Video",
    "packages.card.reddit.title": "Supporto lancio\nReddit",
    "packages.card.reddit.desc":
      "Gestiamo la presenza del tuo studio su Reddit dal suo account ufficiale. 15 post mirati nei subreddit giusti, scritti per adattarsi a ogni community e generare wishlist.",
    "packages.card.pr_starter.title": "PR Starter Pack",
    "packages.card.pr_starter.desc":
      "PR per ottenere copertura: comunicato stampa leggibile, pitch mirati, follow-up e lista completa contatti. Pensato per credibilità e wishlist su Steam.",
    "packages.card.influencer_micro.title": "Influencer\nMicro Campaign",
    "packages.card.influencer_micro.desc":
      "Identifichiamo creator di nicchia, coordiniamo le attivazioni e tracciamo le performance. Economico, scalabile e progettato per una reach di qualità.",
    "packages.card.tiktok_20.title": "Pacchetto TikTok:\n20 video",
    "packages.card.tiktok_20.desc":
      "20 video TikTok su misura per il tuo gioco. Gestiamo concept, produzione e formattazione, in linea con trend di piattaforma e comportamento dell’audience.",
    "packages.card.paid_ads_setup.title": "Setup ads a pagamento",
    "packages.card.paid_ads_setup.desc":
      "Impostiamo le tue campagne paid end-to-end: scelta canali, configurazione budget, targeting e placement creativi. Dopo il lancio, consegniamo l’account. Monitoraggio/ottimizzazione continuativi non inclusi.",
    "packages.card.gameplay_trailer.title": "Gameplay Trailer",
    "packages.card.gameplay_trailer.desc":
      "Trailer gameplay completo e di alta qualità realizzato per il tuo gioco. Storytelling chiaro, capture curata, ritmo, editing e consegna pronta per Steam, YouTube e distribuzione media.",
    "seo.site.name": "Marketing per videogiochi | Marketing per giochi indie",
    "seo.site.description": "TrapPlan aiuta gli studi di videogiochi a far crescere wishlist e vendite con marketing performance-driven.",
    "seo.about.title": "Chi siamo | TrapPlan Agenzia Marketing Videogiochi",
    "seo.about.desc": "TrapPlan aiuta gli studi di videogiochi a far crescere wishlist e vendite con sistemi di marketing basati sulle performance.",
    "seo.blog.title": "Blog di marketing gaming | Trend e consigli",
    "seo.blog.desc":
      "Resta aggiornato sui trend del marketing influencer nel gaming. Il blog TrapPlan include tips, case study e strategie per crescere.",
    "seo.our_cases.title": "I nostri casi | Risultati e case study di marketing gaming",
    "seo.our_cases.desc": "Risultati selezionati e case study di TrapPlan.",
    "seo.no_wishlists.title": "Nessuna wishlist su Steam | Migliora la conversione della pagina",
    "seo.no_wishlists.desc": "Cosa fare quando la tua pagina Steam riceve traffico ma le wishlist non crescono.",
    "seo.reddit_launch_support.title": "Reddit Launch Support: traffico organico senza backlash",
    "seo.reddit_launch_support.desc":
      "Campagna organica Reddit da 15 post per spingere wishlist Steam senza scatenare il classico backlash al marketing.",
    "seo.pr_starter_pack.title": "PR Starter Pack: la copertura che il tuo gioco merita",
    "seo.pr_starter_pack.desc":
      "PR per indie: comunicato stampa leggibile, pitch mirati, follow-up e lista contatti. Per credibilità e wishlist su Steam.",
    "seo.tiktok_20.title": "Pacchetto TikTok: 20 video per campagne marketing gaming",
    "seo.tiktok_20.desc":
      "20 video TikTok per il tuo gioco: hook, script, editing e piano contenuti pensato per awareness e wishlist.",
    "seo.influencer_micro.title": "Influencer Micro Campaign: reach efficiente che converte",
    "seo.influencer_micro.desc":
      "Sprint micro-influencer per giochi: selezione creator di nicchia, outreach, coordinamento, tracking e report. Per reach di qualità e wishlist Steam.",
    "seo.influencer_activation.title": "Attivazione influencer per giochi: copertura che converte",
    "seo.influencer_activation.desc":
      "Campagne influencer strutturate: sourcing, outreach, coordinamento, tracking e learnings post-campagna. Ripetibile, misurabile e pensato per i giochi.",
    "seo.paid_ads_setup.title": "Paid Ads Setup: lancia le campagne nel modo giusto",
    "seo.paid_ads_setup.desc":
      "Impostiamo campagne paid end-to-end: canali, budget, targeting e placement creativi. Dopo il lancio, consegniamo l’account.",
    "seo.gameplay_trailer.title": "Gameplay Trailer: un trailer fatto per convertire",
    "seo.gameplay_trailer.desc":
      "Trailer gameplay completo: storytelling, capture curata, ritmo ed editing. Pronto per Steam, YouTube e distribuzione media.",
    "seo.steam_wishlist_calculator.title": "Calcolatore wishlist Steam | Stima vendite e traffico",
    "seo.steam_wishlist_calculator.desc": "Stima wishlist, traffico e budget necessari per raggiungere l’obiettivo di vendite nella prima settimana.",
    "seo.steam_pricing_planner.title": "Planner e calcolatore prezzi Steam | Strumento prezzi regionali",
    "seo.steam_pricing_planner.desc":
      "Calcola i prezzi regionali consigliati su Steam usando PPP (parità di potere d’acquisto) e cambi FX.",
    "seo.steam_influencers_planner.title": "Planner influencer per Steam | Trova creator gaming per genere",
    "seo.steam_influencers_planner.desc":
      "Strumento professionale per scoprire influencer gaming su YouTube e Twitch in base a genere e giochi simili.",
    "seo.steam_festival_planner.title": "Planner festival Steam | Abbina eventi al tuo gioco",
    "seo.steam_festival_planner.desc":
      "Esplora festival e saldi Steam, filtra per tipo e genere e abbina eventi al tuo gioco con analisi AppID.",
    "seo.creative_content_pipeline.title": "Creative Content Pipeline per Steam e console",
    "seo.creative_content_pipeline.desc":
      "Pipeline continua di trailer, shortform e asset store, con produzione iterativa focalizzata su crescita e conversione delle wishlist.",
    "seo.paid_growth.title": "Paid Growth per Steam e console",
    "seo.paid_growth.desc":
      "Paid growth premium: strategia canali, tracking pulito, attribuzione e handoff strutturato.",
    "seo.game_launch_blueprint.title": "Game Launch Blueprint: la tua strategia, i nostri standard",
    "seo.game_launch_blueprint.desc":
      "Basta tentativi a caso. Forniamo il framework marketing usato dai publisher: standardizzato, testato e pronto da eseguire.",
    "seo.games_co_publishing.title": "Games Co-Publishing: partner marketing e distribuzione",
    "seo.games_co_publishing.desc":
      "Partnership di co-publishing guidata dal marketing: visibilità, validazione di mercato, crescita audience e performance commerciali.",
    "seo.blog.masterclass.title": "Steam Next Fest: masterclass di discovery",
    "seo.blog.masterclass.desc":
      "Deep-dive 2026 su Steam Next Fest: cosa conta, prime 48 ore, segnali di conversione, strategia demo page, timing influencer e come eseguire.",
    "legal.content_rules.meta_title": "Regole dei contenuti | Linee guida TrapPlan",
    "legal.content_rules.meta_desc": "Regole base per usare contenuti e asset di TrapPlan.",
    "legal.content_rules.title": "Regole dei contenuti",
    "legal.content_rules.lede": "Questa pagina definisce come possono essere usati i materiali TrapPlan.",
    "legal.content_rules.section1.title": "1. Proprietà",
    "legal.content_rules.section1.body":
      "Salvo diversa indicazione esplicita, tutti i contenuti di questo sito appartengono a TrapPlan.",
    "legal.content_rules.section2.title": "2. Uso consentito",
    "legal.content_rules.section2.body":
      "Puoi condividere link alle nostre pagine e citare brevi estratti con corretta attribuzione.",
    "legal.content_rules.section3.title": "3. Uso vietato",
    "legal.content_rules.section3.body":
      "Non puoi copiare, ripubblicare o vendere i nostri materiali come se fossero tuoi. Non puoi usare gli asset di brand in modo da suggerire una partnership senza permesso scritto.",
    "legal.content_rules.section4.title": "4. Richieste",
    "legal.content_rules.section4.body":
      "Per riutilizzi oltre quanto descritto sopra, contattaci tramite il modulo sul sito.",
    "legal.copyright.meta_title": "Politica sul copyright | Proprietà intellettuale TrapPlan",
    "legal.copyright.meta_desc": "Politica sul copyright per i contenuti del sito TrapPlan.",
    "legal.copyright.title": "Politica sul copyright",
    "legal.copyright.lede":
      "Questa pagina spiega come i contenuti TrapPlan sono protetti e come puoi utilizzarli.",
    "legal.copyright.section1.title": "Avviso di copyright",
    "legal.copyright.section1.body":
      "Testi, design e materiali su questo sito sono protetti da copyright e da altre leggi applicabili sulla proprietà intellettuale.",
    "legal.copyright.section2.title": "Permesso",
    "legal.copyright.section2.body":
      "Puoi fare riferimento e linkare le nostre pagine. Se vuoi ripubblicare o riprodurre parti sostanziali del contenuto, richiedi l’autorizzazione.",
    "legal.copyright.section3.title": "Segnalazioni",
    "legal.copyright.section3.body":
      "Se ritieni che un’opera protetta sia usata su questo sito in modo illecito, contattaci includendo i dettagli rilevanti.",
    "footer.tagline":
      "Dal primo annuncio al lancio globale. Workflow di marketing di livello professionale, progettati specificamente per gli studi di videogiochi che vogliono risultati migliori e zero caos.",
    "footer.notice_at_collection": "Avviso sulla raccolta",
    "footer.privacy_choices": "Le tue scelte sulla privacy",
    "about.hero.title": "Chi è TrapPlan",
    "about.hero.subtitle":
      "Aiutiamo gli studi di videogiochi a far crescere in modo prevedibile wishlist e vendite combinando strategia, messaggi chiari ed esecuzione orientata alla performance.",
    "about.hero.cta_primary": "Lavora con noi",
    "about.hero.cta_secondary": "Leggi il blog",
    "about.how_we_think.title": "Come ragioniamo",
    "about.how_we_think.body":
      "Costruiamo sistemi che rendono il marketing ripetibile. Non “più attività”: una catena chiara da posizionamento ad asset, distribuzione e misurazione.",
    "about.principle.01.title": "Strategia adatta alla tua fase",
    "about.principle.01.body":
      "Niente consigli generici. Trasformiamo la tua realtà (team, timeline, audience, asset store) in un piano di lancio e crescita eseguibile.",
    "about.principle.02.title": "Messaggi che convertono",
    "about.principle.02.body":
      "Ti aiutiamo a comunicare la promessa del tuo gioco su Steam, creatività e campagne, così i giocatori giusti capiscono subito.",
    "about.principle.03.title": "Esecuzione con misurazione",
    "about.principle.03.body":
      "Lavoriamo con cicli strutturati, tracking pulito, ownership chiara e post-mortem per migliorare ogni iterazione.",
    "about.what_you_get.title": "Cosa ottieni",
    "about.what_you_get.body": "Una collaborazione strutturata che riduce il caos e rende le decisioni misurabili.",
    "about.outcome.label": "RISULTATO",
    "about.outcome.01.title": "Priorità chiare",
    "about.outcome.01.body": "Un piano che collega milestone e attività marketing, con responsabilità e scadenze.",
    "about.outcome.02.title": "Conversione migliore",
    "about.outcome.02.body": "Messaggi e asset ottimizzati per ridurre dubbi e aumentare l’intento.",
    "about.outcome.03.title": "Tracking pulito",
    "about.outcome.03.body": "Un layer di misurazione per capire quali canali e creatività funzionano.",
    "about.outcome.04.title": "Apprendimenti ripetibili",
    "about.outcome.04.body": "Post-mortem e iterazioni che si accumulano nel tempo invece di ripartire da zero.",
    "about.principles.title": "Principi",
    "about.principles.body": "Come collaboriamo con gli studi: i non negoziabili.",
    "about.value.04.title": "Processo trasparente e prevedibile",
    "about.value.04.body":
      "Sai sempre cosa stiamo facendo, perché e che aspetto ha il successo. Deliverable chiari, cadenza e log delle decisioni.",
    "about.value.05.title": "Mentalità performance",
    "about.value.05.body": "Ci concentriamo su ciò che conta: conversione, velocità di wishlist e canali di acquisizione ripetibili.",
    "about.value.06.title": "Pensato per gli studi",
    "about.value.06.body":
      "Progettiamo tenendo conto della produzione: poco tempo, priorità che cambiano e vincoli sugli asset, senza abbassare l’asticella.",
    "form_page.title": "Potenzia il tuo marketing\ncon un piano che funziona",
    "form_page.subtitle":
      "Ti aiutiamo a chiarire gli obiettivi, scegliere i formati giusti e tornare con un piano chiaro — anche se non sai da dove iniziare.",
    "form_page.bullet.01": "Allinearti ai tuoi obiettivi",
    "form_page.bullet.02": "Scoprire formati ad alte performance",
    "form_page.bullet.03": "Ricevere una proposta chiara e concreta",
    "work_with_us_form.field_full_name": "Nome e cognome*",
    "work_with_us_form.field_company": "Nome azienda*",
    "work_with_us_form.field_email": "tu@azienda.com*",
    "work_with_us_form.field_message": "Raccontaci del tuo gioco o di cosa hai bisogno...",
    "work_with_us_form.subscribe": "Vorrei ricevere occasionalmente consigli di marketing",
    "work_with_us_form.submit_sending": "Invio...",
    "work_with_us_form.submit": "Parliamone",
    "work_with_us_form.privacy_note": "Non condivideremo mai i tuoi dati. Ti contatterà un solo esperto.",
    "work_with_us_form.success": "Grazie! Ti contatteremo presto.",
    "work_with_us_form.error_generic": "Qualcosa è andato storto. Riprova.",
    "work_with_us_form.error_network": "Invio non riuscito. Riprova.",
    "form.get_a_quote.title": "RICHIEDI UN PREVENTIVO",
    "form.get_a_quote.subtitle":
      "Parliamo della tua esigenza, poi torneremo con un'offerta finale.",
    "form.get_a_quote.message_whatsapp": "Messaggio su WhatsApp",
    "form.get_a_quote.card_title": "Lavoriamo insieme",
    "form.get_a_quote.field_name": "Nome*",
    "form.get_a_quote.field_company": "Nome dell’azienda*",
    "form.get_a_quote.field_email": "Email di lavoro*",
    "form.get_a_quote.submit_sending": "Invio...",
    "form.get_a_quote.submit_send": "Invia",
    "form.get_a_quote.success": "Grazie! Ti contatteremo presto.",
    "form.get_a_quote.error_generic": "Qualcosa è andato storto. Riprova.",
    "form.get_a_quote.error_network": "Invio non riuscito. Riprova.",
    "blog_quote_banner.banner.title": "Vuoi aiuto con il piano marketing del tuo gioco?",
    "blog_quote_banner.banner.subtitle": "Invia una richiesta rapida e ti risponderemo con i prossimi passi",
    "blog_quote_banner.banner.cta": "Richiedi un preventivo",
    "blog_quote_banner.modal.title": "Lavoriamo insieme",
    "blog_quote_banner.modal.subtitle": "Condividi i tuoi dettagli e ti contatteremo",
    "blog_quote_banner.modal.close": "Chiudi",
    "blog_quote_banner.success": "Grazie! Ti contatteremo presto.",
    "blog_quote_banner.error_generic": "Qualcosa è andato storto. Riprova.",
    "blog_quote_banner.error_network": "Invio non riuscito. Riprova.",
    "no_wishlists.ui.title": "Nessuna wishlist su Steam",
    "no_wishlists.ui.subtitle": "Una pagina pratica e breve da condividere. Nessun embed esterno, nessun contenuto CDN.",
    "no_wishlists.ui.reasons.title": "Motivi comuni",
    "no_wishlists.ui.reasons.body": "La crescita bassa delle wishlist è solitamente un problema di conversione, non di traffico. La promessa della pagina dello store potrebbe non essere chiara, la capsule potrebbe non generare clic, o la pagina non corrisponde al traffico che stai inviando.",
    "no_wishlists.ui.fix.title": "Cosa sistemare prima",
    "no_wishlists.ui.fix.body": "Inizia con il posizionamento, la chiarezza della capsule e del trailer breve, poi migliora la parte superiore della pagina (primo scroll) e valida con un tracciamento pulito.",
    "no_wishlists.ui.tools.title": "Strumenti utili",
    "no_wishlists.ui.tools.body": "Usa il nostro calcolatore per impostare obiettivi realistici e verificare la tua velocità attuale.",
    "no_wishlists.ui.tools.cta": "Calcolatore Wishlist Steam",
    "our_cases.ui.title": "I nostri casi",
    "our_cases.ui.subtitle": "Una selezione di risultati. Condividiamo ciò che è utile pubblicamente e manteniamo i dettagli sensibili privati.",
    "our_cases.ui.view_case_study": "Vedi caso studio",
    "our_cases.ui.next_step": "PROSSIMO PASSO",
    "our_cases.ui.next_step_title": "Vuoi un risultato simile?",
    "our_cases.ui.next_step_body": "Condividi la tua timeline e i tuoi obiettivi. Ti proporremo un piano ripetibile e mostreremo esempi rilevanti.",
    "our_cases.ui.contact_us": "Contattaci",
    "studios_cases.ui.back_to_cases": "← Torna ai casi",
    "studios_cases.ui.case_snapshot": "PANORAMICA DEL CASO",
    "studios_cases.ui.client": "Cliente",
    "studios_cases.ui.date": "Data",
    "studios_cases.ui.note": "Nota",
    "studios_cases.ui.note_body": "Questa pagina è memorizzata nel repository e non carica contenuti esterni.",
    "studios_cases.ui.work_with_us": "Lavora con noi",
    "studios_cases.ui.next_step": "PROSSIMO PASSO",
    "studios_cases.ui.next_step_title": "Vuoi un risultato simile?",
    "studios_cases.ui.next_step_body": "Condividi la tua fase attuale e i vincoli. Ti proporremo un piano ripetibile.",
    "studios_cases.ui.contact_us": "Contattaci",
    "studios_cases.ui.summary": "Riepilogo",
    "studios_cases.ui.no_sections": "Questo caso non ha ancora sezioni dettagliate.",
    "blog.ui.sidebar_title": "Trap Plan\nBlog",
    "blog.ui.sidebar_subtitle": "Note, guide e sistemi pratici di marketing per videogiochi.",
    "blog.ui.sidebar_latest": "Ultimi",
    "blog.ui.sidebar_all": "Tutti",
    "pr_starter_pack.ui.hero.body_connector_1": ". Un buon articolo funziona come un",
    "pr_starter_pack.ui.hero.body_connector_2": "e spinge più giocatori a premere",
    "blog.masterclass.s01.title": 'Steam Next Fest: Migliaia di giochi competeranno, ma come ottieni risultati?',
    "blog.masterclass.s01.p01": 'Steam Next Fest non è più un posto dove basta presentarsi. Con migliaia di demo in competizione contemporaneamente, la piattaforma premierà i progetti preparati e penalizzerà quelli che trattano il festival come punto di partenza. Questa guida spiega cosa conta davvero nel 2026, quali segnali Steam osserva e come trasformare la settimana in slancio misurabile.',
    "blog.masterclass.s02.title": 'Il Fest di febbraio è dietro l’angolo e ho appena finito la mia demo. Dovrei partecipare adesso?',
    "blog.masterclass.s02.p01": 'Jordan avverte che Next Fest non è più la "pallottola magica" del 2023 quando partecipavano meno di 1.000 giochi. Oggi, con oltre 3.000 giochi in competizione regolare, l’ambiente è molto meno indulgente.',
    "blog.masterclass.s02.p02": 'Se usi il festival come modo per iniziare il tuo marketing da zero, probabilmente stai commettendo un errore. La strategia ideale è lanciare la demo almeno qualche mese prima dell’evento per correggere bug e costruire trazione iniziale.',
    "blog.masterclass.s02.p03": 'I giochi che entrano a Next Fest con una base sostanziale di wishlist agiscono come moltiplicatore dello slancio esistente, mentre quelli che partono da freddo spesso si ritrovano sepolti dall’algoritmo.',
    "blog.masterclass.s03.title": 'Dicono che i livestream non funzionano più. Posso saltare la trasmissione?',
    "blog.masterclass.s03.p01": 'Il panorama è cambiato: Steam ha de-prioritizzato i livestream e non forniscono più l’enorme spinta di visibilità di una volta. Tuttavia, non è un motivo per saltarli completamente, poiché la sezione dedicata alle trasmissioni attive esiste ancora e offre un livello di scoperta.',
    "blog.masterclass.s03.p02": 'Invece di esaurirti con sessioni live di 10 ore, usa strumenti come Robostreamer per riprodurre in loop filmati di gameplay di alta qualità o, meglio ancora, un influencer noto che gioca al tuo gioco. Questo ti permette di mantenere una presenza nella rotazione senza esaurire risorse meglio spese interagendo con la tua comunità su Discord.',
    "blog.masterclass.s04.title": 'L’algoritmo di Steam è cambiato a fine 2024. Cosa devo sapere sulle prime 48 ore?',
    "blog.masterclass.s04.p01": 'Questa è una finestra critica: nei primi due giorni del festival, tutti i giochi ricevono visibilità approssimativamente uguale perché le liste sono ordinate casualmente.',
    "blog.masterclass.s04.p02": 'Tuttavia, dopo queste 48 ore, Steam passa a modelli di machine learning che personalizzano il feed per ogni utente in base ai suoi interessi specifici e a cosa giocano i suoi amici.',
    "blog.masterclass.s04.p03": 'I dati di interazione che Steam raccoglie durante quei primi due giorni — clic, download e interazioni — formano la base di come l’algoritmo categorizza e raccomanda il tuo gioco per il resto della settimana. Essenzialmente, le prime 48 ore "addestrano" il sistema su chi è il tuo pubblico.',
    "blog.masterclass.s05.title": 'Steam traccia davvero se le persone finiscono la mia demo?',
    "blog.masterclass.s05.p01": 'Sorprendentemente, no. Nelle sessioni ufficiali di Q&A, Valve ha dichiarato che i tassi di completamento delle demo e il tempo totale di gioco non sono segnali decisivi per la visibilità post-fest. Ritengono che sarebbe ingiusto giudicare un’esperienza narrativa di 20 minuti contro un roguelike giocabile all’infinito.',
    "blog.masterclass.s05.p02": 'Invece, Steam si concentra sui "segnali di interazione": quante persone hanno visitato la tua pagina dello store, scaricato la demo e, soprattutto, quante hanno aggiunto alla wishlist o seguito il tuo progetto.',
    "blog.masterclass.s05.p03": 'Concentrati sulla conversione — trasformare un clic in una wishlist — piuttosto che cercare di forzare i giocatori a restare nella demo per ore.',
    "blog.masterclass.s06.title": 'Perché usare una pagina separata per la demo se posso semplicemente aggiungere un pulsante alla pagina principale?',
    "blog.masterclass.s06.p01": 'Una pagina demo separata è il tuo strumento principale per costruire prova sociale. Ti permette di raccogliere recensioni specifiche per la demo, che è un segnale potente. Se ottieni molte recensioni positive, può aiutarti a comparire nelle classifiche "Tendenza Gratis", portando un’ondata massiccia di nuovo traffico.',
    "blog.masterclass.s06.p02": 'Al contrario, se la demo riceve feedback negativi, puoi semplicemente rimuovere la pagina separata senza influenzare la reputazione della tua pagina principale dello store.',
    "blog.masterclass.s06.p03": 'È un modo sicuro per testare la prontezza del tuo prodotto per il mercato, e se sei ancora nervoso, usa prima gli strumenti Steam Playtest, dove il feedback rimane privato.',
    "blog.masterclass.s07.title": 'Ho inviato email agli influencer il giorno prima del fest. Perché nessuno risponde?',
    "blog.masterclass.s07.p01": 'Probabilmente sei in ritardo. Il lavoro PR efficace con stampa e creatori deve iniziare almeno un mese prima. Il primo contatto dovrebbe avvenire quattro settimane prima dell’inizio, offrendo una key con una data di embargo chiara così i creatori hanno tempo di programmare i loro contenuti.',
    "blog.masterclass.s07.p02": 'Fai un follow-up con un promemoria una settimana prima dell’evento e una "spinta" finale il giorno di apertura.',
    "blog.masterclass.s07.p03": 'Non fare spam a tutti; costruisci una lista curata di creatori di nicchia che apprezzano genuinamente il tuo genere. Ricorda che più di tre email di solito superano il limite della fastidiosità e possono danneggiare la tua reputazione a lungo termine.',
    "blog.masterclass.s08.title": 'Come faccio a far tornare i giocatori il secondo o terzo giorno del festival?',
    "blog.masterclass.s08.p01": 'Usa tattiche di "ritenzione attraverso l’engagement" per mantenere attiva la tua comunità. Tiny Glade lo ha fatto brillantemente offrendo temi di costruzione giornalieri, mentre Tears of Metal ha introdotto modificatori di gameplay giornalieri per mantenere l’esperienza fresca.',
    "blog.masterclass.s08.p02": 'Puoi sbloccare ricompense cosmetiche esclusive per il gioco completo se i giocatori completano la demo durante finestre specifiche, o ospitare devlog giornalieri con anteprime delle prossime funzionalità.',
    "blog.masterclass.s08.p03": 'Una delle mosse più potenti è sfruttare il FOMO offrendo una ricompensa unica per giocare entro le prime 24 ore, garantendo alte prestazioni durante quella finestra critica di raccolta dati di 48 ore.',
    "blog.masterclass.s09.title": 'Il mio gioco ha bug, ma dovrei continuare a sviluppare nuove funzionalità durante il fest?',
    "blog.masterclass.s09.p01": 'Dimentica le nuove funzionalità durante la settimana del festival. Il tuo unico lavoro ora è "spegnere incendi". Sii disponibile 24/7 per correggere immediatamente bug critici e rispondere ai feedback.',
    "blog.masterclass.s09.p02": 'Una risposta rapida da parte di uno sviluppatore è il modo migliore per trasformare un giocatore frustrato in un fan appassionato. Se ignori i report di bug durante Next Fest, perdi la buona volontà dei giocatori che non può essere ricomprata con nessuna quantità di pubblicità.',
    "blog.masterclass.s09.p03": 'Configura strumenti automatizzati di segnalazione bug direttamente nel menu principale o nella schermata di pausa così i giocatori possono contattarti istantaneamente invece di lasciare una recensione negativa.',
    "blog.masterclass.s10.title": 'Ho sentito parlare di "achievement" nelle demo. È davvero una buona idea?',
    "blog.masterclass.s10.p01": 'Non è solo una buona idea; è una necessità per l’engagement. Aggiungere Achievement Steam alla tua demo è un modo provato per motivare i giocatori.',
    "blog.masterclass.s10.p02": 'Includi un achievement facile nei primi 15 minuti per "agganciare" il giocatore e mostrargli che le ricompense sono raggiungibili. Aggiungine un altro per completare la demo come incentivo finale per finire l’esperienza.',
    "blog.masterclass.s10.p03": 'Un mix di achievement divertenti e difficili trasforma una semplice demo in una sfida gratificante, che si correla direttamente con il desiderio del giocatore di portare quel progresso nel gioco completo aggiungendolo alla wishlist.',
    "blog.masterclass.s11.title": 'Perché non dovrei lanciare il mio gioco subito dopo la fine del festival?',
    "blog.masterclass.s11.p01": 'È una trappola comune: il desiderio di "battere il ferro finché è caldo" porta molti sviluppatori a lanciare esattamente nello stesso momento di centinaia di altri partecipanti di Next Fest.',
    "blog.masterclass.s11.p02": 'Durante questa finestra, la competizione per un posto in "Nuovi e in Tendenza" è anormalmente alta, e rischi di essere spinto fuori da studi più grandi con budget maggiori.',
    "blog.masterclass.s11.p03": 'A meno che tu non abbia almeno 20.000 wishlist e sia sicuro di essere stato uno dei migliori del fest, spesso è meglio aspettare. Lascia che il mercato si raffreddi, continua ad aggiornare la tua demo e mantieni la connessione con il tuo nuovo pubblico per una finestra di lancio più stabile.',
};

export default translations;
