import type { CopyKey } from "@/lib/copy";

const translations: Partial<Record<CopyKey, string>> = {
    "seo.site.name": "游戏营销 | 独立游戏营销",
    "seo.site.description": "TrapPlan 通过以效果为导向的营销，帮助游戏工作室增长愿望单与销量。",
    "seo.about.title": "关于我们 | TrapPlan 游戏营销代理",
    "seo.about.desc": "TrapPlan 通过以效果为导向的营销系统，帮助游戏工作室增长愿望单与销量。",
    "seo.blog.title": "游戏营销博客｜趋势与实用技巧",
    "seo.blog.desc": "跟进游戏营销最新趋势。TrapPlan 博客分享实用技巧、案例与策略，帮助品牌在游戏行业取得增长。",
    "seo.our_cases.title": "案例 | 游戏营销成果与案例研究",
    "seo.our_cases.desc": "TrapPlan 精选成果与案例研究。",
    "seo.no_wishlists.title": "Steam 上没有愿望单 | 提升商店页面转化率",
    "seo.no_wishlists.desc": "当 Steam 页面有流量但愿望单不增长时，应该优先修复什么。",
    "seo.reddit_launch_support.title": "Reddit 发售支持：无反感的自然流量",
    "seo.reddit_launch_support.desc": "15 条高互动的 Reddit 自然内容投放，帮助提升 Steam 愿望单，并避免常见营销反感。",
    "seo.pr_starter_pack.title": "PR 入门包：为你的游戏争取报道",
    "seo.pr_starter_pack.desc": "面向独立游戏的 PR 外联：易读的新闻稿、精准投递、跟进，以及清晰的联系人列表。用于建立可信度并提升 Steam 愿望单。",
    "seo.tiktok_20.title": "TikTok 套餐：20 条视频 | 游戏营销推广方案",
    "seo.tiktok_20.desc": "为你的游戏制作 20 条 TikTok 视频：hook、脚本、剪辑与内容计划，目标是提升愿望单与认知。",
    "seo.influencer_micro.title": "达人微型投放：高性价比的可转化曝光",
    "seo.influencer_micro.desc": "面向游戏的微型达人激活冲刺：选择与匹配、外联、协同、追踪与报告。聚焦有效触达与 Steam 愿望单。",
    "seo.paid_ads_setup.title": "付费广告搭建：正确启动你的投放",
    "seo.paid_ads_setup.desc": "从渠道选择到预算、定向与素材位设置，我们完成完整投放搭建并交接账号。后续持续监控/优化不包含在内。",
    "seo.gameplay_trailer.title": "Gameplay Trailer：为转化而生的预告片",
    "seo.gameplay_trailer.desc": "为你的游戏制作完整 gameplay trailer：清晰叙事、优质录制、节奏、剪辑，并交付可用于 Steam、YouTube 与媒体传播的版本。",
    "seo.steam_wishlist_calculator.title": "Steam 愿望单计算器 | 估算销量与流量目标",
    "seo.steam_wishlist_calculator.desc": "估算达成 Steam 首周销量目标所需的愿望单、流量与预算。",
    "seo.steam_pricing_planner.title": "Steam 定价规划器与计算器 | 区域定价工具",
    "seo.steam_pricing_planner.desc": "使用购买力平价（PPP）与实时汇率计算推荐的 Steam 区域定价。",
    "seo.steam_influencers_planner.title": "Steam 达人规划器 | 按类型查找游戏创作者",
    "seo.steam_influencers_planner.desc": "基于题材与相似游戏，发现 YouTube/Twitch 游戏达人并规划投放。",
    "seo.steam_festival_planner.title": "Steam 活动规划器 | 为你的游戏匹配活动",
    "seo.steam_festival_planner.desc": "浏览 Steam 节日与促销，按类型/题材筛选，并用 AppID 分析匹配适合你游戏的活动。",
    "seo.creative_content_pipeline.title": "Steam/主机创意内容流水线",
    "seo.creative_content_pipeline.desc": "持续产出 trailer、短视频与商店素材的内容流水线，迭代制作，聚焦愿望单增长与转化。",
    "seo.paid_growth.title": "Steam/主机付费增长",
    "seo.paid_growth.desc": "高客单价付费增长：渠道策略、清晰追踪、归因与结构化交接。",
    "seo.game_launch_blueprint.title": "发售蓝图：你的策略，我们的标准",
    "seo.game_launch_blueprint.desc": "别再猜下一步。我们提供发行商使用的营销框架：标准化、久经验证，并可一起落地执行。",
    "seo.games_co_publishing.title": "联合发行：营销与分发合作伙伴",
    "seo.games_co_publishing.desc": "以营销驱动的联合发行合作：提升可见度、市场验证、受众增长与商业表现。",
    "seo.blog.masterclass.title": "Steam Next Fest：发现机制深度解析",
    "seo.blog.masterclass.desc": "2026 深度解读 Steam Next Fest：关键因素、前 48 小时、转化信号、demo 页面策略、达人节奏与如何落地执行。",
    "seo.influencer_activation.title": "面向游戏的达人投放：带来可转化的曝光",
    "seo.influencer_activation.desc":
      "结构化达人营销：筛选与匹配、外联、协同执行、追踪与复盘。可重复、可衡量，专为游戏打造。",
    "legal.content_rules.meta_title": "内容规则 | TrapPlan 使用指南",
    "legal.content_rules.meta_desc": "关于使用 TrapPlan 内容与素材的基本规则。",
    "legal.content_rules.title": "内容规则",
    "legal.content_rules.lede": "本页面说明 TrapPlan 材料的使用方式。",
    "legal.content_rules.section1.title": "1. 所有权",
    "legal.content_rules.section1.body": "除非另有明确说明，本网站的所有内容均归 TrapPlan 所有。",
    "legal.content_rules.section2.title": "2. 允许的使用",
    "legal.content_rules.section2.body": "你可以分享我们页面的链接，并在注明出处的情况下引用短段内容。",
    "legal.content_rules.section3.title": "3. 禁止的使用",
    "legal.content_rules.section3.body":
      "你不得将我们的材料复制、再发布或作为自己的内容出售。未经书面许可，不得以暗示合作关系的方式使用我们的品牌素材。",
    "legal.content_rules.section4.title": "4. 申请",
    "legal.content_rules.section4.body": "如需超出上述范围使用材料，请通过本网站表单联系我们。",
    "legal.copyright.meta_title": "版权政策 | TrapPlan 知识产权",
    "legal.copyright.meta_desc": "TrapPlan 网站内容的版权政策。",
    "legal.copyright.title": "版权政策",
    "legal.copyright.lede":
      "本页面说明 TrapPlan 内容的版权保护方式以及你可以如何使用。",
    "legal.copyright.section1.title": "版权声明",
    "legal.copyright.section1.body":
      "本网站的文字、设计与材料受版权及其他适用的知识产权法律保护。",
    "legal.copyright.section2.title": "许可",
    "legal.copyright.section2.body":
      "你可以引用并链接到我们的页面。如需转载或复制网站内容的重要部分，请先申请许可。",
    "legal.copyright.section3.title": "举报",
    "legal.copyright.section3.body":
      "如果你认为你的作品在本网站上的使用构成侵权，请联系我们并提供相关细节。",
    "footer.tagline":
      "从首次发布到全球上线。为游戏工作室量身打造的专业营销工作流，带来更好的结果与更少的混乱。",
    "footer.notice_at_collection": "数据收集告知",
    "footer.privacy_choices": "隐私选项",
    "about.hero.title": "关于 TrapPlan",
    "about.hero.subtitle":
      "我们通过策略、清晰的表达与以效果为导向的执行，帮助游戏工作室实现可预测的愿望单与销售增长。",
    "about.hero.cta_primary": "与我们合作",
    "about.hero.cta_secondary": "阅读博客",
    "about.how_we_think.title": "我们的思路",
    "about.how_we_think.body":
      "我们打造可重复的营销系统。不是“更多动作”，而是一条从定位到素材到分发到衡量的清晰链路。",
    "about.principle.01.title": "匹配阶段的策略",
    "about.principle.01.body":
      "拒绝泛泛建议。我们把你的现实情况（团队、周期、受众、商店素材）转化为你能真正落地的发行与增长计划。",
    "about.principle.02.title": "能转化的信息表达",
    "about.principle.02.body":
      "我们帮助你在 Steam 页面、创意素材与投放中清晰传达游戏核心卖点，让目标玩家快速理解。",
    "about.principle.03.title": "可衡量的执行",
    "about.principle.03.body":
      "结构化节奏、干净的追踪、明确的负责人和复盘机制，让每次迭代都更接近结果。",
    "about.what_you_get.title": "你会得到什么",
    "about.what_you_get.body": "一套结构化的合作方式，减少混乱，让决策可衡量。",
    "about.outcome.label": "结果",
    "about.outcome.01.title": "清晰优先级",
    "about.outcome.01.body": "把里程碑映射到营销节奏，明确负责人和截止时间。",
    "about.outcome.02.title": "更高转化",
    "about.outcome.02.body": "优化信息表达与商店素材，减少困惑、提升意图。",
    "about.outcome.03.title": "清晰追踪",
    "about.outcome.03.body": "搭建衡量层，快速看清哪些渠道和创意有效。",
    "about.outcome.04.title": "可复用的经验",
    "about.outcome.04.body": "复盘与迭代会持续累积，而不是每次从零开始。",
    "about.principles.title": "原则",
    "about.principles.body": "我们与工作室协作的“底线规则”。",
    "about.value.04.title": "透明、可预期的流程",
    "about.value.04.body": "你始终知道我们在做什么、为什么做，以及成功是什么样子。交付物、节奏与决策记录都清晰。",
    "about.value.05.title": "结果导向",
    "about.value.05.body": "专注于真正有效的指标：商店转化、愿望单增长速度，以及可复制的获客渠道。",
    "about.value.06.title": "为游戏工作室而生",
    "about.value.06.body": "我们围绕制作现实设计：时间有限、优先级变化、素材受限——但不降低质量标准。",
    "form_page.title": "让你的游戏营销\n更进一步",
    "form_page.subtitle":
      "我们会帮助你理清目标、选择合适的推广形式，并给出一份清晰的方案——即使你还不知道从哪里开始。",
    "form_page.bullet.01": "与目标对齐",
    "form_page.bullet.02": "找到高表现的推广形式",
    "form_page.bullet.03": "获得清晰可执行的方案",
    "work_with_us_form.field_full_name": "姓名*",
    "work_with_us_form.field_company": "公司名称*",
    "work_with_us_form.field_email": "你@你的公司.com*",
    "work_with_us_form.field_message": "介绍一下你的游戏，或你需要我们帮助的内容…",
    "work_with_us_form.subscribe": "我愿意偶尔接收营销技巧",
    "work_with_us_form.submit_sending": "发送中...",
    "work_with_us_form.submit": "开始沟通",
    "work_with_us_form.privacy_note": "我们不会分享你的信息。只会有一位专家与你联系。",
    "work_with_us_form.success": "感谢！我们会尽快联系你。",
    "work_with_us_form.error_generic": "出错了，请重试。",
    "work_with_us_form.error_network": "发送失败，请重试。",
    "form.get_a_quote.title": "获取报价",
    "form.get_a_quote.subtitle": "先聊聊你的需求，我们会整理后带着最终报价回复你。",
    "form.get_a_quote.message_whatsapp": "通过 WhatsApp 联系",
    "form.get_a_quote.card_title": "一起合作",
    "form.get_a_quote.field_name": "姓名*",
    "form.get_a_quote.field_company": "公司名称*",
    "form.get_a_quote.field_email": "工作邮箱*",
    "form.get_a_quote.submit_sending": "发送中...",
    "form.get_a_quote.submit_send": "发送",
    "form.get_a_quote.success": "感谢！我们会尽快联系你。",
    "form.get_a_quote.error_generic": "出错了，请重试。",
    "form.get_a_quote.error_network": "发送失败，请重试。",
    "blog_quote_banner.banner.title": "需要帮助制定你的游戏营销计划吗",
    "blog_quote_banner.banner.subtitle": "发送一个简短请求，我们会回复下一步",
    "blog_quote_banner.banner.cta": "获取报价",
    "blog_quote_banner.modal.title": "一起合作吧",
    "blog_quote_banner.modal.subtitle": "留下你的信息，我们会联系你",
    "blog_quote_banner.modal.close": "关闭",
    "blog_quote_banner.success": "感谢！我们会尽快联系你。",
    "blog_quote_banner.error_generic": "出错了，请重试。",
    "blog_quote_banner.error_network": "发送失败，请重试。",
    "no_wishlists.ui.title": "没有Steam愿望单",
    "no_wishlists.ui.subtitle": "一个简短实用的页面，可以直接分享。无外部嵌入，无CDN内容。",
    "no_wishlists.ui.reasons.title": "常见原因",
    "no_wishlists.ui.reasons.body": "愿望单增长缓慢通常是转化问题，而非流量问题。商店页面的承诺可能不清晰，胶囊图可能无法吸引点击，或者页面与你发送的流量不匹配。",
    "no_wishlists.ui.fix.title": "先修复什么",
    "no_wishlists.ui.fix.body": "从定位、胶囊图和短预告片的清晰度开始，然后改善页面顶部（第一屏），并通过干净的跟踪进行验证。",
    "no_wishlists.ui.tools.title": "实用工具",
    "no_wishlists.ui.tools.body": "使用我们的计算器设定切实的目标，并检查你当前的速度。",
    "no_wishlists.ui.tools.cta": "Steam愿望单计算器",
    "our_cases.ui.title": "我们的案例",
    "our_cases.ui.subtitle": "精选的成果展示。我们公开分享有用的内容，敏感细节保密。",
    "our_cases.ui.view_case_study": "查看案例",
    "our_cases.ui.next_step": "下一步",
    "our_cases.ui.next_step_title": "想要类似的结果？",
    "our_cases.ui.next_step_body": "分享你的时间表和目标。我们会提出可重复的计划并展示相关案例。",
    "our_cases.ui.contact_us": "联系我们",
    "studios_cases.ui.back_to_cases": "← 返回案例",
    "studios_cases.ui.case_snapshot": "案例概览",
    "studios_cases.ui.client": "客户",
    "studios_cases.ui.date": "日期",
    "studios_cases.ui.note": "说明",
    "studios_cases.ui.note_body": "此页面存储在代码仓库中，不加载任何外部内容。",
    "studios_cases.ui.work_with_us": "与我们合作",
    "studios_cases.ui.next_step": "下一步",
    "studios_cases.ui.next_step_title": "想要类似的结果？",
    "studios_cases.ui.next_step_body": "分享你当前的阶段和限制。我们会提出可重复的计划。",
    "studios_cases.ui.contact_us": "联系我们",
    "studios_cases.ui.summary": "摘要",
    "studios_cases.ui.no_sections": "此案例尚无详细章节。",
    "blog.ui.sidebar_title": "Trap Plan\nBlog",
    "blog.ui.sidebar_subtitle": "笔记、指南和实用的游戏营销系统。",
    "blog.ui.sidebar_latest": "最新",
    "blog.ui.sidebar_all": "全部",
    "pr_starter_pack.ui.hero.body_connector_1": "。一篇好文章就像一个",
    "pr_starter_pack.ui.hero.body_connector_2": "并推动更多玩家点击",
    "blog.masterclass.s01.title": "Steam Next Fest：数千款游戏将参与竞争，但你如何获得成果？",
    "blog.masterclass.s01.p01": "Steam Next Fest 不再是一个露个面就够的地方。数千款 demo 同时竞争，平台会奖励有准备的项目，惩罚把节日当起点的项目。本指南解释了 2026 年真正重要的是什么、Steam 关注哪些信号，以及如何将这一周转化为可衡量的动力。",
    "blog.masterclass.s02.title": "二月 Fest 即将到来，我刚完成 demo。我应该现在参加吗？",
    "blog.masterclass.s02.p01": "Jordan 警告说，Next Fest 不再是 2023 年不到 1000 款游戏参与时的“魔法子弹”。如今，超过 3000 款游戏定期参与竞争，环境远没有那么宽容。",
    "blog.masterclass.s02.p02": "如果你把节日当作从零开始营销的方式，你很可能在犯错。理想的策略是在活动前至少几个月发布你的 demo，以修复 bug 并建立初始牵引力。",
    "blog.masterclass.s02.p03": "带着大量愿望单基础进入 Next Fest 的游戏会成为现有动力的倍增器，而冷启动的游戏往往会被算法埋没。",
    "blog.masterclass.s03.title": "人们说直播不再有效了。我可以跳过直播吗？",
    "blog.masterclass.s03.p01": "格局已经改变：Steam 降低了直播的优先级，它们不再提供曾经的巨大曝光提升。然而，这不是完全跳过它们的理由，因为活跃直播的专用区域仍然存在，并提供一层可发现性。",
    "blog.masterclass.s03.p02": "与其用 10 小时的直播耗尽自己，不如使用 Robostreamer 等工具循环播放高质量的游戏画面，或者更好的是，一个知名主播在玩你的游戏。这让你能在轮播中保持存在感，而不会耗尽更适合在 Discord 上与社区互动的资源。",
    "blog.masterclass.s04.title": "Steam 算法在 2024 年底发生了变化。关于前 48 小时我需要知道什么？",
    "blog.masterclass.s04.p01": "这是一个关键窗口：在节日的前两天，所有游戏获得大致相等的曝光，因为列表是随机排序的。",
    "blog.masterclass.s04.p02": "然而，在这 48 小时之后，Steam 切换到机器学习模型，根据每个登录用户的特定兴趣和朋友在玩什么来个性化推送。",
    "blog.masterclass.s04.p03": "Steam 在前两天收集的互动数据——点击、下载和互动——构成了算法如何在剩余一周内分类和推荐你的游戏的基础。本质上，前 48 小时“训练”系统了解你的受众是谁。",
    "blog.masterclass.s05.title": "Steam 真的会追踪人们是否完成了我的 demo 吗？",
    "blog.masterclass.s05.p01": "令人惊讶的是，不会。在官方问答环节中，Valve 表示 demo 完成率和总游戏时间不是节后可见性的决定性信号。他们认为将 20 分钟的叙事体验与可以无限玩下去的 roguelike 进行比较是不公平的。",
    "blog.masterclass.s05.p02": "相反，Steam 关注的是“互动信号”：有多少人访问了你的商店页面、下载了 demo，最重要的是，有多少人加入了愿望单或关注了你的项目。",
    "blog.masterclass.s05.p03": "专注于转化——将点击转化为愿望单——而不是试图强迫玩家在 demo 中停留数小时。",
    "blog.masterclass.s06.title": "为什么要为 demo 使用单独的页面，而不是在主页面上添加一个按钮？",
    "blog.masterclass.s06.p01": "单独的 demo 页面是你建立社会证明的主要工具。它允许你收集 demo 的特定评价，这是一个强大的信号。如果你获得大量正面评价，它可以帮助你登上“热门免费”排行榜，带来大量新流量。",
    "blog.masterclass.s06.p02": "相反，如果 demo 收到负面反馈，你可以简单地撤下单独的页面，而不影响主商店页面的声誉。",
    "blog.masterclass.s06.p03": "这是测试产品市场准备度的安全方式，如果你仍然紧张，可以先使用 Steam Playtest 工具，反馈保持私密。",
    "blog.masterclass.s07.title": "我在节日前一天给网红发了邮件。为什么没人回复？",
    "blog.masterclass.s07.p01": "你可能太晚了。与媒体和创作者的有效公关工作必须至少提前一个月开始。你的第一次联系应该在开始前四周进行，提供一个带有明确解禁日期的密钥，以便创作者有时间安排他们的内容。",
    "blog.masterclass.s07.p02": "在活动前一周发送提醒跟进，并在开幕日做最后的“推动”。",
    "blog.masterclass.s07.p03": "不要给所有人发垃圾邮件；建立一个真正喜欢你的游戏类型的小众创作者精选列表。记住，超过三封邮件通常会越过骚扰的界限，可能损害你的长期声誉。",
    "blog.masterclass.s08.title": "如何让玩家在节日的第二天或第三天回来？",
    "blog.masterclass.s08.p01": "使用“通过参与度留存”策略来保持社区活跃。Tiny Glade 通过提供每日建造主题做得很出色，而 Tears of Metal 引入了每日游戏修改器来保持体验新鲜。",
    "blog.masterclass.s08.p02": "你可以在玩家在特定时间窗口内完成 demo 时解锁完整游戏的独家装饰奖励，或举办每日开发日志，展示即将推出的功能预览。",
    "blog.masterclass.s08.p03": "最强大的举措之一是利用 FOMO，在前 24 小时内提供独特的游戏奖励，确保在关键的 48 小时数据收集窗口期间保持高性能。",
    "blog.masterclass.s09.title": "我的游戏有 bug，但我应该在节日期间继续开发新功能吗？",
    "blog.masterclass.s09.p01": "忘掉节日那周的新功能吧。你现在唯一的工作是“救火”。24/7 随时待命，立即修复关键 bug 并回应反馈。",
    "blog.masterclass.s09.p02": "开发者的快速回应是将沮丧的玩家转变为热情粉丝的最佳方式。如果你在 Next Fest 期间忽略 bug 报告，你将失去任何广告都买不回来的玩家好感。",
    "blog.masterclass.s09.p03": "在主菜单或暂停屏幕中直接设置自动化 bug 报告工具，这样玩家可以立即联系你，而不是留下负面评价。",
    "blog.masterclass.s10.title": "我听说 demo 中有“成就”。这真的是个好主意吗？",
    "blog.masterclass.s10.p01": "这不仅是个好主意；对于参与度来说是必需的。在你的 demo 中添加 Steam 成就是激励玩家的有效方式。",
    "blog.masterclass.s10.p02": "在前 15 分钟内包含一个简单的成就来“钩住”玩家，向他们展示奖励是可以获得的。再添加一个完成 demo 的成就作为完成体验的最终激励。",
    "blog.masterclass.s10.p03": "有趣和困难成就的混合将简单的 demo 变成有回报的挑战，这与玩家希望通过加入愿望单将进度带入完整游戏的愿望直接相关。",
    "blog.masterclass.s11.title": "为什么我不应该在节日结束后立即发布我的游戏？",
    "blog.masterclass.s11.p01": "这是一个常见的陷阱：“趁热打铁”的愿望导致许多开发者与数百名其他 Next Fest 参与者在完全相同的时间发布。",
    "blog.masterclass.s11.p02": "在这个窗口期间，“新品和热门”中的位置竞争异常激烈，你有被预算更大的大型工作室挤出的风险。",
    "blog.masterclass.s11.p03": "除非你至少有 20,000 个愿望单并且确信自己是节日中绝对的顶级表现者之一，否则通常最好等待。让市场冷却下来，继续更新你的 demo，并与新受众保持联系，以获得更稳定的发布窗口。",
    "ui.pagination.previous": "上一页",
    "ui.pagination.next": "下一页",
    "ui.pagination.page_aria": "跳转至第 {n} 页",
    "ui.mobile_cta.label": "申请报价",
    "ui.cookie.title": "我们使用 Cookie。",
    "ui.cookie.body": "一组最少的 Cookie 让网站正常运行。在你同意后，匿名分析帮助我们了解哪些内容真正帮助了工作室。在你接受之前，不会激活任何第三方追踪器。",
    "ui.cookie.accept": "全部接受",
    "ui.cookie.reject": "拒绝非必要",
    "ui.cookie.learn_more": "了解更多",
    "ui.breadcrumb.home": "首页",
    "ui.breadcrumb.blog": "博客",
    "ui.breadcrumb.our_cases": "案例研究",
    "ui.breadcrumb.about": "关于",
    "services_hub.title": "我们为游戏工作室提供的全部服务。",
    "services_hub.subtitle": "选择你今天需要的服务，或将多个服务组合成完整项目。所有项目都由同一个出货过游戏的高级团队负责。",
    "services_hub.cta_learn_more": "了解更多 →",
    "services_hub.packages_title": "固定范围套餐",
    "services_hub.packages_subtitle": "更小的合作，价格清晰、范围清晰、交付物清晰。",
};

export default translations;
